package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompBossOrderTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public CompBossOrderTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBossOrderIdIsNull() {
			addCriterion("BOSS_ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdIsNotNull() {
			addCriterion("BOSS_ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdEqualTo(String value) {
			addCriterion("BOSS_ORDER_ID =", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdNotEqualTo(String value) {
			addCriterion("BOSS_ORDER_ID <>", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdGreaterThan(String value) {
			addCriterion("BOSS_ORDER_ID >", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("BOSS_ORDER_ID >=", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdLessThan(String value) {
			addCriterion("BOSS_ORDER_ID <", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdLessThanOrEqualTo(String value) {
			addCriterion("BOSS_ORDER_ID <=", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdLike(String value) {
			addCriterion("BOSS_ORDER_ID like", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdNotLike(String value) {
			addCriterion("BOSS_ORDER_ID not like", value, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdIn(List<String> values) {
			addCriterion("BOSS_ORDER_ID in", values, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdNotIn(List<String> values) {
			addCriterion("BOSS_ORDER_ID not in", values, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdBetween(String value1, String value2) {
			addCriterion("BOSS_ORDER_ID between", value1, value2, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andBossOrderIdNotBetween(String value1, String value2) {
			addCriterion("BOSS_ORDER_ID not between", value1, value2, "bossOrderId");
			return (Criteria) this;
		}

		public Criteria andOperateTypeIsNull() {
			addCriterion("OPERATE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andOperateTypeIsNotNull() {
			addCriterion("OPERATE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andOperateTypeEqualTo(String value) {
			addCriterion("OPERATE_TYPE =", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeNotEqualTo(String value) {
			addCriterion("OPERATE_TYPE <>", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeGreaterThan(String value) {
			addCriterion("OPERATE_TYPE >", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATE_TYPE >=", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeLessThan(String value) {
			addCriterion("OPERATE_TYPE <", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeLessThanOrEqualTo(String value) {
			addCriterion("OPERATE_TYPE <=", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeLike(String value) {
			addCriterion("OPERATE_TYPE like", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeNotLike(String value) {
			addCriterion("OPERATE_TYPE not like", value, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeIn(List<String> values) {
			addCriterion("OPERATE_TYPE in", values, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeNotIn(List<String> values) {
			addCriterion("OPERATE_TYPE not in", values, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeBetween(String value1, String value2) {
			addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
			return (Criteria) this;
		}

		public Criteria andOperateTypeNotBetween(String value1, String value2) {
			addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeIsNull() {
			addCriterion("REASON_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andReasonTypeIsNotNull() {
			addCriterion("REASON_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andReasonTypeEqualTo(String value) {
			addCriterion("REASON_TYPE =", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeNotEqualTo(String value) {
			addCriterion("REASON_TYPE <>", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeGreaterThan(String value) {
			addCriterion("REASON_TYPE >", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeGreaterThanOrEqualTo(String value) {
			addCriterion("REASON_TYPE >=", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeLessThan(String value) {
			addCriterion("REASON_TYPE <", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeLessThanOrEqualTo(String value) {
			addCriterion("REASON_TYPE <=", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeLike(String value) {
			addCriterion("REASON_TYPE like", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeNotLike(String value) {
			addCriterion("REASON_TYPE not like", value, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeIn(List<String> values) {
			addCriterion("REASON_TYPE in", values, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeNotIn(List<String> values) {
			addCriterion("REASON_TYPE not in", values, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeBetween(String value1, String value2) {
			addCriterion("REASON_TYPE between", value1, value2, "reasonType");
			return (Criteria) this;
		}

		public Criteria andReasonTypeNotBetween(String value1, String value2) {
			addCriterion("REASON_TYPE not between", value1, value2, "reasonType");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeIsNull() {
			addCriterion("AGREEMENT_BEGING_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeIsNotNull() {
			addCriterion("AGREEMENT_BEGING_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeEqualTo(String value) {
			addCriterion("AGREEMENT_BEGING_TIME =", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeNotEqualTo(String value) {
			addCriterion("AGREEMENT_BEGING_TIME <>", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeGreaterThan(String value) {
			addCriterion("AGREEMENT_BEGING_TIME >", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeGreaterThanOrEqualTo(String value) {
			addCriterion("AGREEMENT_BEGING_TIME >=", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeLessThan(String value) {
			addCriterion("AGREEMENT_BEGING_TIME <", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeLessThanOrEqualTo(String value) {
			addCriterion("AGREEMENT_BEGING_TIME <=", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeLike(String value) {
			addCriterion("AGREEMENT_BEGING_TIME like", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeNotLike(String value) {
			addCriterion("AGREEMENT_BEGING_TIME not like", value, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeIn(List<String> values) {
			addCriterion("AGREEMENT_BEGING_TIME in", values, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeNotIn(List<String> values) {
			addCriterion("AGREEMENT_BEGING_TIME not in", values, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeBetween(String value1, String value2) {
			addCriterion("AGREEMENT_BEGING_TIME between", value1, value2, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementBegingTimeNotBetween(String value1, String value2) {
			addCriterion("AGREEMENT_BEGING_TIME not between", value1, value2, "agreementBegingTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeIsNull() {
			addCriterion("AGREEMENT_END_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeIsNotNull() {
			addCriterion("AGREEMENT_END_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeEqualTo(String value) {
			addCriterion("AGREEMENT_END_TIME =", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeNotEqualTo(String value) {
			addCriterion("AGREEMENT_END_TIME <>", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeGreaterThan(String value) {
			addCriterion("AGREEMENT_END_TIME >", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeGreaterThanOrEqualTo(String value) {
			addCriterion("AGREEMENT_END_TIME >=", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeLessThan(String value) {
			addCriterion("AGREEMENT_END_TIME <", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeLessThanOrEqualTo(String value) {
			addCriterion("AGREEMENT_END_TIME <=", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeLike(String value) {
			addCriterion("AGREEMENT_END_TIME like", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeNotLike(String value) {
			addCriterion("AGREEMENT_END_TIME not like", value, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeIn(List<String> values) {
			addCriterion("AGREEMENT_END_TIME in", values, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeNotIn(List<String> values) {
			addCriterion("AGREEMENT_END_TIME not in", values, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeBetween(String value1, String value2) {
			addCriterion("AGREEMENT_END_TIME between", value1, value2, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndTimeNotBetween(String value1, String value2) {
			addCriterion("AGREEMENT_END_TIME not between", value1, value2, "agreementEndTime");
			return (Criteria) this;
		}

		public Criteria andResourceTypeIsNull() {
			addCriterion("RESOURCE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andResourceTypeIsNotNull() {
			addCriterion("RESOURCE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andResourceTypeEqualTo(String value) {
			addCriterion("RESOURCE_TYPE =", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeNotEqualTo(String value) {
			addCriterion("RESOURCE_TYPE <>", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeGreaterThan(String value) {
			addCriterion("RESOURCE_TYPE >", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
			addCriterion("RESOURCE_TYPE >=", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeLessThan(String value) {
			addCriterion("RESOURCE_TYPE <", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeLessThanOrEqualTo(String value) {
			addCriterion("RESOURCE_TYPE <=", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeLike(String value) {
			addCriterion("RESOURCE_TYPE like", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeNotLike(String value) {
			addCriterion("RESOURCE_TYPE not like", value, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeIn(List<String> values) {
			addCriterion("RESOURCE_TYPE in", values, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeNotIn(List<String> values) {
			addCriterion("RESOURCE_TYPE not in", values, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeBetween(String value1, String value2) {
			addCriterion("RESOURCE_TYPE between", value1, value2, "resourceType");
			return (Criteria) this;
		}

		public Criteria andResourceTypeNotBetween(String value1, String value2) {
			addCriterion("RESOURCE_TYPE not between", value1, value2, "resourceType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeIsNull() {
			addCriterion("CHARGE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andChargeTypeIsNotNull() {
			addCriterion("CHARGE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andChargeTypeEqualTo(String value) {
			addCriterion("CHARGE_TYPE =", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeNotEqualTo(String value) {
			addCriterion("CHARGE_TYPE <>", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeGreaterThan(String value) {
			addCriterion("CHARGE_TYPE >", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CHARGE_TYPE >=", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeLessThan(String value) {
			addCriterion("CHARGE_TYPE <", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeLessThanOrEqualTo(String value) {
			addCriterion("CHARGE_TYPE <=", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeLike(String value) {
			addCriterion("CHARGE_TYPE like", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeNotLike(String value) {
			addCriterion("CHARGE_TYPE not like", value, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeIn(List<String> values) {
			addCriterion("CHARGE_TYPE in", values, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeNotIn(List<String> values) {
			addCriterion("CHARGE_TYPE not in", values, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeBetween(String value1, String value2) {
			addCriterion("CHARGE_TYPE between", value1, value2, "chargeType");
			return (Criteria) this;
		}

		public Criteria andChargeTypeNotBetween(String value1, String value2) {
			addCriterion("CHARGE_TYPE not between", value1, value2, "chargeType");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("PRICE is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("PRICE is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(String value) {
			addCriterion("PRICE =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(String value) {
			addCriterion("PRICE <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(String value) {
			addCriterion("PRICE >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(String value) {
			addCriterion("PRICE >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(String value) {
			addCriterion("PRICE <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(String value) {
			addCriterion("PRICE <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLike(String value) {
			addCriterion("PRICE like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotLike(String value) {
			addCriterion("PRICE not like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<String> values) {
			addCriterion("PRICE in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<String> values) {
			addCriterion("PRICE not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(String value1, String value2) {
			addCriterion("PRICE between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(String value1, String value2) {
			addCriterion("PRICE not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeIsNull() {
			addCriterion("PAYMENT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeIsNotNull() {
			addCriterion("PAYMENT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeEqualTo(String value) {
			addCriterion("PAYMENT_TYPE =", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeNotEqualTo(String value) {
			addCriterion("PAYMENT_TYPE <>", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeGreaterThan(String value) {
			addCriterion("PAYMENT_TYPE >", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_TYPE >=", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeLessThan(String value) {
			addCriterion("PAYMENT_TYPE <", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_TYPE <=", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeLike(String value) {
			addCriterion("PAYMENT_TYPE like", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeNotLike(String value) {
			addCriterion("PAYMENT_TYPE not like", value, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeIn(List<String> values) {
			addCriterion("PAYMENT_TYPE in", values, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeNotIn(List<String> values) {
			addCriterion("PAYMENT_TYPE not in", values, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeBetween(String value1, String value2) {
			addCriterion("PAYMENT_TYPE between", value1, value2, "paymentType");
			return (Criteria) this;
		}

		public Criteria andPaymentTypeNotBetween(String value1, String value2) {
			addCriterion("PAYMENT_TYPE not between", value1, value2, "paymentType");
			return (Criteria) this;
		}

		public Criteria andTimeStampIsNull() {
			addCriterion("TIME_STAMP is null");
			return (Criteria) this;
		}

		public Criteria andTimeStampIsNotNull() {
			addCriterion("TIME_STAMP is not null");
			return (Criteria) this;
		}

		public Criteria andTimeStampEqualTo(String value) {
			addCriterion("TIME_STAMP =", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotEqualTo(String value) {
			addCriterion("TIME_STAMP <>", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampGreaterThan(String value) {
			addCriterion("TIME_STAMP >", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampGreaterThanOrEqualTo(String value) {
			addCriterion("TIME_STAMP >=", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLessThan(String value) {
			addCriterion("TIME_STAMP <", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLessThanOrEqualTo(String value) {
			addCriterion("TIME_STAMP <=", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLike(String value) {
			addCriterion("TIME_STAMP like", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotLike(String value) {
			addCriterion("TIME_STAMP not like", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampIn(List<String> values) {
			addCriterion("TIME_STAMP in", values, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotIn(List<String> values) {
			addCriterion("TIME_STAMP not in", values, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampBetween(String value1, String value2) {
			addCriterion("TIME_STAMP between", value1, value2, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotBetween(String value1, String value2) {
			addCriterion("TIME_STAMP not between", value1, value2, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_boss_order_t
     *
     * @mbggenerated do_not_delete_during_merge Thu May 03 16:40:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}