package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompResPoolT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String resPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.RES_POOL_NAME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String resPoolName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.RES_POOL_ZONE
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String resPoolZone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.RES_POOL_URL
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String resPoolUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.USER_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.USER_PWD
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_res_pool_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.RES_POOL_ID
	 * @return  the value of comp_res_pool_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getResPoolId() {
		return resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.RES_POOL_ID
	 * @param resPoolId  the value for comp_res_pool_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setResPoolId(String resPoolId) {
		this.resPoolId = resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.RES_POOL_NAME
	 * @return  the value of comp_res_pool_t.RES_POOL_NAME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getResPoolName() {
		return resPoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.RES_POOL_NAME
	 * @param resPoolName  the value for comp_res_pool_t.RES_POOL_NAME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setResPoolName(String resPoolName) {
		this.resPoolName = resPoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.RES_POOL_ZONE
	 * @return  the value of comp_res_pool_t.RES_POOL_ZONE
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getResPoolZone() {
		return resPoolZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.RES_POOL_ZONE
	 * @param resPoolZone  the value for comp_res_pool_t.RES_POOL_ZONE
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setResPoolZone(String resPoolZone) {
		this.resPoolZone = resPoolZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.RES_POOL_URL
	 * @return  the value of comp_res_pool_t.RES_POOL_URL
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getResPoolUrl() {
		return resPoolUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.RES_POOL_URL
	 * @param resPoolUrl  the value for comp_res_pool_t.RES_POOL_URL
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setResPoolUrl(String resPoolUrl) {
		this.resPoolUrl = resPoolUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.USER_ID
	 * @return  the value of comp_res_pool_t.USER_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.USER_ID
	 * @param userId  the value for comp_res_pool_t.USER_ID
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.USER_PWD
	 * @return  the value of comp_res_pool_t.USER_PWD
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.USER_PWD
	 * @param userPwd  the value for comp_res_pool_t.USER_PWD
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.STATUS
	 * @return  the value of comp_res_pool_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.STATUS
	 * @param status  the value for comp_res_pool_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.DESCRIPTION
	 * @return  the value of comp_res_pool_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.DESCRIPTION
	 * @param description  the value for comp_res_pool_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.CREATE_TIME
	 * @return  the value of comp_res_pool_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.CREATE_TIME
	 * @param createTime  the value for comp_res_pool_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.CREATE_USER
	 * @return  the value of comp_res_pool_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.CREATE_USER
	 * @param createUser  the value for comp_res_pool_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.UPDATE_TIME
	 * @return  the value of comp_res_pool_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.UPDATE_TIME
	 * @param updateTime  the value for comp_res_pool_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_res_pool_t.UPDATE_USER
	 * @return  the value of comp_res_pool_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_res_pool_t.UPDATE_USER
	 * @param updateUser  the value for comp_res_pool_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}