package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompAuthorityUserT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.USER_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.PASSWORD
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.STATUS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.LOCK_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String lockTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.MOBILE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.EMAIL
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.ADDRESS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.LOGIN_FAILED_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String loginFailedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.TELPHONE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.FAX
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.DEPARTMENT_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.FORBIDDEN_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String forbiddenTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.LOCK_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String lockNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.FORBIDDEN_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String forbiddenNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.SECURITY_QUESTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String securityQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.SECURITY_ANSWER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String securityAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_t.CHARGES_USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	private String chargesUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.USER_ID
	 * @return  the value of comp_authority_user_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.USER_ID
	 * @param userId  the value for comp_authority_user_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.USER_NAME
	 * @return  the value of comp_authority_user_t.USER_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.USER_NAME
	 * @param userName  the value for comp_authority_user_t.USER_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.PASSWORD
	 * @return  the value of comp_authority_user_t.PASSWORD
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.PASSWORD
	 * @param password  the value for comp_authority_user_t.PASSWORD
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.CREATE_TIME
	 * @return  the value of comp_authority_user_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.CREATE_TIME
	 * @param createTime  the value for comp_authority_user_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.UPDATE_TIME
	 * @return  the value of comp_authority_user_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.UPDATE_TIME
	 * @param updateTime  the value for comp_authority_user_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.STATUS
	 * @return  the value of comp_authority_user_t.STATUS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.STATUS
	 * @param status  the value for comp_authority_user_t.STATUS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.LOCK_TIME
	 * @return  the value of comp_authority_user_t.LOCK_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.LOCK_TIME
	 * @param lockTime  the value for comp_authority_user_t.LOCK_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setLockTime(String lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.MOBILE
	 * @return  the value of comp_authority_user_t.MOBILE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.MOBILE
	 * @param mobile  the value for comp_authority_user_t.MOBILE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.EMAIL
	 * @return  the value of comp_authority_user_t.EMAIL
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.EMAIL
	 * @param email  the value for comp_authority_user_t.EMAIL
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.ADDRESS
	 * @return  the value of comp_authority_user_t.ADDRESS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.ADDRESS
	 * @param address  the value for comp_authority_user_t.ADDRESS
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.DESCRIPTION
	 * @return  the value of comp_authority_user_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.DESCRIPTION
	 * @param description  the value for comp_authority_user_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.CREATE_USER
	 * @return  the value of comp_authority_user_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.CREATE_USER
	 * @param createUser  the value for comp_authority_user_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.LOGIN_FAILED_TIME
	 * @return  the value of comp_authority_user_t.LOGIN_FAILED_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getLoginFailedTime() {
		return loginFailedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.LOGIN_FAILED_TIME
	 * @param loginFailedTime  the value for comp_authority_user_t.LOGIN_FAILED_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setLoginFailedTime(String loginFailedTime) {
		this.loginFailedTime = loginFailedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.TELPHONE
	 * @return  the value of comp_authority_user_t.TELPHONE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.TELPHONE
	 * @param telphone  the value for comp_authority_user_t.TELPHONE
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.FAX
	 * @return  the value of comp_authority_user_t.FAX
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.FAX
	 * @param fax  the value for comp_authority_user_t.FAX
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.DEPARTMENT_NAME
	 * @return  the value of comp_authority_user_t.DEPARTMENT_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.DEPARTMENT_NAME
	 * @param departmentName  the value for comp_authority_user_t.DEPARTMENT_NAME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.FORBIDDEN_TIME
	 * @return  the value of comp_authority_user_t.FORBIDDEN_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getForbiddenTime() {
		return forbiddenTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.FORBIDDEN_TIME
	 * @param forbiddenTime  the value for comp_authority_user_t.FORBIDDEN_TIME
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setForbiddenTime(String forbiddenTime) {
		this.forbiddenTime = forbiddenTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.LOCK_NUM
	 * @return  the value of comp_authority_user_t.LOCK_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getLockNum() {
		return lockNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.LOCK_NUM
	 * @param lockNum  the value for comp_authority_user_t.LOCK_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setLockNum(String lockNum) {
		this.lockNum = lockNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.FORBIDDEN_NUM
	 * @return  the value of comp_authority_user_t.FORBIDDEN_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getForbiddenNum() {
		return forbiddenNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.FORBIDDEN_NUM
	 * @param forbiddenNum  the value for comp_authority_user_t.FORBIDDEN_NUM
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setForbiddenNum(String forbiddenNum) {
		this.forbiddenNum = forbiddenNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.SECURITY_QUESTION
	 * @return  the value of comp_authority_user_t.SECURITY_QUESTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getSecurityQuestion() {
		return securityQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.SECURITY_QUESTION
	 * @param securityQuestion  the value for comp_authority_user_t.SECURITY_QUESTION
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.SECURITY_ANSWER
	 * @return  the value of comp_authority_user_t.SECURITY_ANSWER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getSecurityAnswer() {
		return securityAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.SECURITY_ANSWER
	 * @param securityAnswer  the value for comp_authority_user_t.SECURITY_ANSWER
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setSecurityAnswer(String securityAnswer) {
		this.securityAnswer = securityAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_t.CHARGES_USER_ID
	 * @return  the value of comp_authority_user_t.CHARGES_USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getChargesUserId() {
		return chargesUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_t.CHARGES_USER_ID
	 * @param chargesUserId  the value for comp_authority_user_t.CHARGES_USER_ID
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setChargesUserId(String chargesUserId) {
		this.chargesUserId = chargesUserId;
	}
}