package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompAuthorityUserAppTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public CompAuthorityUserAppTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("APP_ID is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("APP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("APP_ID =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("APP_ID <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("APP_ID >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("APP_ID >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("APP_ID <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("APP_ID <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("APP_ID like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("APP_ID not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("APP_ID in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("APP_ID not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("APP_ID between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("APP_ID not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusIsNull() {
			addCriterion("APPBIND_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusIsNotNull() {
			addCriterion("APPBIND_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusEqualTo(String value) {
			addCriterion("APPBIND_STATUS =", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusNotEqualTo(String value) {
			addCriterion("APPBIND_STATUS <>", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusGreaterThan(String value) {
			addCriterion("APPBIND_STATUS >", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusGreaterThanOrEqualTo(String value) {
			addCriterion("APPBIND_STATUS >=", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusLessThan(String value) {
			addCriterion("APPBIND_STATUS <", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusLessThanOrEqualTo(String value) {
			addCriterion("APPBIND_STATUS <=", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusLike(String value) {
			addCriterion("APPBIND_STATUS like", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusNotLike(String value) {
			addCriterion("APPBIND_STATUS not like", value, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusIn(List<String> values) {
			addCriterion("APPBIND_STATUS in", values, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusNotIn(List<String> values) {
			addCriterion("APPBIND_STATUS not in", values, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusBetween(String value1, String value2) {
			addCriterion("APPBIND_STATUS between", value1, value2, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAppbindStatusNotBetween(String value1, String value2) {
			addCriterion("APPBIND_STATUS not between", value1, value2, "appbindStatus");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIsNull() {
			addCriterion("AUDIT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIsNotNull() {
			addCriterion("AUDIT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAuditTimeEqualTo(String value) {
			addCriterion("AUDIT_TIME =", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotEqualTo(String value) {
			addCriterion("AUDIT_TIME <>", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeGreaterThan(String value) {
			addCriterion("AUDIT_TIME >", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_TIME >=", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeLessThan(String value) {
			addCriterion("AUDIT_TIME <", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_TIME <=", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeLike(String value) {
			addCriterion("AUDIT_TIME like", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotLike(String value) {
			addCriterion("AUDIT_TIME not like", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIn(List<String> values) {
			addCriterion("AUDIT_TIME in", values, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotIn(List<String> values) {
			addCriterion("AUDIT_TIME not in", values, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeBetween(String value1, String value2) {
			addCriterion("AUDIT_TIME between", value1, value2, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotBetween(String value1, String value2) {
			addCriterion("AUDIT_TIME not between", value1, value2, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditUserIsNull() {
			addCriterion("AUDIT_USER is null");
			return (Criteria) this;
		}

		public Criteria andAuditUserIsNotNull() {
			addCriterion("AUDIT_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAuditUserEqualTo(String value) {
			addCriterion("AUDIT_USER =", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserNotEqualTo(String value) {
			addCriterion("AUDIT_USER <>", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserGreaterThan(String value) {
			addCriterion("AUDIT_USER >", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_USER >=", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserLessThan(String value) {
			addCriterion("AUDIT_USER <", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_USER <=", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserLike(String value) {
			addCriterion("AUDIT_USER like", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserNotLike(String value) {
			addCriterion("AUDIT_USER not like", value, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserIn(List<String> values) {
			addCriterion("AUDIT_USER in", values, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserNotIn(List<String> values) {
			addCriterion("AUDIT_USER not in", values, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserBetween(String value1, String value2) {
			addCriterion("AUDIT_USER between", value1, value2, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditUserNotBetween(String value1, String value2) {
			addCriterion("AUDIT_USER not between", value1, value2, "auditUser");
			return (Criteria) this;
		}

		public Criteria andAuditInfoIsNull() {
			addCriterion("AUDIT_INFO is null");
			return (Criteria) this;
		}

		public Criteria andAuditInfoIsNotNull() {
			addCriterion("AUDIT_INFO is not null");
			return (Criteria) this;
		}

		public Criteria andAuditInfoEqualTo(String value) {
			addCriterion("AUDIT_INFO =", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoNotEqualTo(String value) {
			addCriterion("AUDIT_INFO <>", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoGreaterThan(String value) {
			addCriterion("AUDIT_INFO >", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_INFO >=", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoLessThan(String value) {
			addCriterion("AUDIT_INFO <", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_INFO <=", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoLike(String value) {
			addCriterion("AUDIT_INFO like", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoNotLike(String value) {
			addCriterion("AUDIT_INFO not like", value, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoIn(List<String> values) {
			addCriterion("AUDIT_INFO in", values, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoNotIn(List<String> values) {
			addCriterion("AUDIT_INFO not in", values, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoBetween(String value1, String value2) {
			addCriterion("AUDIT_INFO between", value1, value2, "auditInfo");
			return (Criteria) this;
		}

		public Criteria andAuditInfoNotBetween(String value1, String value2) {
			addCriterion("AUDIT_INFO not between", value1, value2, "auditInfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_authority_user_app_t
     *
     * @mbggenerated do_not_delete_during_merge Wed May 02 14:59:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}