package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompAuthorityUserAppT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.APPBIND_STATUS
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String appbindStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.AUDIT_TIME
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String auditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.AUDIT_USER
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String auditUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_authority_user_app_t.AUDIT_INFO
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	private String auditInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.USER_ID
	 * @return  the value of comp_authority_user_app_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.USER_ID
	 * @param userId  the value for comp_authority_user_app_t.USER_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.APP_ID
	 * @return  the value of comp_authority_user_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.APP_ID
	 * @param appId  the value for comp_authority_user_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.APPBIND_STATUS
	 * @return  the value of comp_authority_user_app_t.APPBIND_STATUS
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getAppbindStatus() {
		return appbindStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.APPBIND_STATUS
	 * @param appbindStatus  the value for comp_authority_user_app_t.APPBIND_STATUS
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setAppbindStatus(String appbindStatus) {
		this.appbindStatus = appbindStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.AUDIT_TIME
	 * @return  the value of comp_authority_user_app_t.AUDIT_TIME
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getAuditTime() {
		return auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.AUDIT_TIME
	 * @param auditTime  the value for comp_authority_user_app_t.AUDIT_TIME
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setAuditTime(String auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.AUDIT_USER
	 * @return  the value of comp_authority_user_app_t.AUDIT_USER
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getAuditUser() {
		return auditUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.AUDIT_USER
	 * @param auditUser  the value for comp_authority_user_app_t.AUDIT_USER
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setAuditUser(String auditUser) {
		this.auditUser = auditUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_authority_user_app_t.AUDIT_INFO
	 * @return  the value of comp_authority_user_app_t.AUDIT_INFO
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public String getAuditInfo() {
		return auditInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_authority_user_app_t.AUDIT_INFO
	 * @param auditInfo  the value for comp_authority_user_app_t.AUDIT_INFO
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	public void setAuditInfo(String auditInfo) {
		this.auditInfo = auditInfo;
	}
}