package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompCaseVlanT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.VLAN_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String vlanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.VLAN_NAME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String vlanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String resPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String resPoolPartId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.ZONE_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String zoneType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.VLAN_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String vlanType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CANCELED
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String canceled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CANCEL_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String cancelTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_vlan_t.CANCEL_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	private String cancelUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CASE_ID
	 * @return  the value of comp_case_vlan_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CASE_ID
	 * @param caseId  the value for comp_case_vlan_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.VLAN_ID
	 * @return  the value of comp_case_vlan_t.VLAN_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getVlanId() {
		return vlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.VLAN_ID
	 * @param vlanId  the value for comp_case_vlan_t.VLAN_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setVlanId(String vlanId) {
		this.vlanId = vlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.VLAN_NAME
	 * @return  the value of comp_case_vlan_t.VLAN_NAME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getVlanName() {
		return vlanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.VLAN_NAME
	 * @param vlanName  the value for comp_case_vlan_t.VLAN_NAME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setVlanName(String vlanName) {
		this.vlanName = vlanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.ORDER_ID
	 * @return  the value of comp_case_vlan_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.ORDER_ID
	 * @param orderId  the value for comp_case_vlan_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.APP_ID
	 * @return  the value of comp_case_vlan_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.APP_ID
	 * @param appId  the value for comp_case_vlan_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.RES_POOL_ID
	 * @return  the value of comp_case_vlan_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getResPoolId() {
		return resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.RES_POOL_ID
	 * @param resPoolId  the value for comp_case_vlan_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setResPoolId(String resPoolId) {
		this.resPoolId = resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.RES_POOL_PART_ID
	 * @return  the value of comp_case_vlan_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getResPoolPartId() {
		return resPoolPartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.RES_POOL_PART_ID
	 * @param resPoolPartId  the value for comp_case_vlan_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setResPoolPartId(String resPoolPartId) {
		this.resPoolPartId = resPoolPartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.ZONE_TYPE
	 * @return  the value of comp_case_vlan_t.ZONE_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getZoneType() {
		return zoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.ZONE_TYPE
	 * @param zoneType  the value for comp_case_vlan_t.ZONE_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setZoneType(String zoneType) {
		this.zoneType = zoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.VLAN_TYPE
	 * @return  the value of comp_case_vlan_t.VLAN_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getVlanType() {
		return vlanType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.VLAN_TYPE
	 * @param vlanType  the value for comp_case_vlan_t.VLAN_TYPE
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setVlanType(String vlanType) {
		this.vlanType = vlanType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CREATE_TIME
	 * @return  the value of comp_case_vlan_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CREATE_TIME
	 * @param createTime  the value for comp_case_vlan_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CREATE_USER
	 * @return  the value of comp_case_vlan_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CREATE_USER
	 * @param createUser  the value for comp_case_vlan_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CANCELED
	 * @return  the value of comp_case_vlan_t.CANCELED
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCanceled() {
		return canceled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CANCELED
	 * @param canceled  the value for comp_case_vlan_t.CANCELED
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCanceled(String canceled) {
		this.canceled = canceled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CANCEL_TIME
	 * @return  the value of comp_case_vlan_t.CANCEL_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCancelTime() {
		return cancelTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CANCEL_TIME
	 * @param cancelTime  the value for comp_case_vlan_t.CANCEL_TIME
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCancelTime(String cancelTime) {
		this.cancelTime = cancelTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_vlan_t.CANCEL_USER
	 * @return  the value of comp_case_vlan_t.CANCEL_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public String getCancelUser() {
		return cancelUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_vlan_t.CANCEL_USER
	 * @param cancelUser  the value for comp_case_vlan_t.CANCEL_USER
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	public void setCancelUser(String cancelUser) {
		this.cancelUser = cancelUser;
	}
}