package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompAuthorityUserTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public CompAuthorityUserTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("USER_NAME in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("USER_NAME not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(String value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(String value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(String value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(String value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLike(String value) {
			addCriterion("UPDATE_TIME like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotLike(String value) {
			addCriterion("UPDATE_TIME not like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<String> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<String> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andLockTimeIsNull() {
			addCriterion("LOCK_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLockTimeIsNotNull() {
			addCriterion("LOCK_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLockTimeEqualTo(String value) {
			addCriterion("LOCK_TIME =", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeNotEqualTo(String value) {
			addCriterion("LOCK_TIME <>", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeGreaterThan(String value) {
			addCriterion("LOCK_TIME >", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeGreaterThanOrEqualTo(String value) {
			addCriterion("LOCK_TIME >=", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeLessThan(String value) {
			addCriterion("LOCK_TIME <", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeLessThanOrEqualTo(String value) {
			addCriterion("LOCK_TIME <=", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeLike(String value) {
			addCriterion("LOCK_TIME like", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeNotLike(String value) {
			addCriterion("LOCK_TIME not like", value, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeIn(List<String> values) {
			addCriterion("LOCK_TIME in", values, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeNotIn(List<String> values) {
			addCriterion("LOCK_TIME not in", values, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeBetween(String value1, String value2) {
			addCriterion("LOCK_TIME between", value1, value2, "lockTime");
			return (Criteria) this;
		}

		public Criteria andLockTimeNotBetween(String value1, String value2) {
			addCriterion("LOCK_TIME not between", value1, value2, "lockTime");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("MOBILE is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("MOBILE is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("MOBILE =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("MOBILE <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("MOBILE >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILE >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("MOBILE <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("MOBILE <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("MOBILE like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("MOBILE not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("MOBILE in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("MOBILE not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("MOBILE between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("MOBILE not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("ADDRESS in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("ADDRESS not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeIsNull() {
			addCriterion("LOGIN_FAILED_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeIsNotNull() {
			addCriterion("LOGIN_FAILED_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeEqualTo(String value) {
			addCriterion("LOGIN_FAILED_TIME =", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeNotEqualTo(String value) {
			addCriterion("LOGIN_FAILED_TIME <>", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeGreaterThan(String value) {
			addCriterion("LOGIN_FAILED_TIME >", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_FAILED_TIME >=", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeLessThan(String value) {
			addCriterion("LOGIN_FAILED_TIME <", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_FAILED_TIME <=", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeLike(String value) {
			addCriterion("LOGIN_FAILED_TIME like", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeNotLike(String value) {
			addCriterion("LOGIN_FAILED_TIME not like", value, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeIn(List<String> values) {
			addCriterion("LOGIN_FAILED_TIME in", values, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeNotIn(List<String> values) {
			addCriterion("LOGIN_FAILED_TIME not in", values, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeBetween(String value1, String value2) {
			addCriterion("LOGIN_FAILED_TIME between", value1, value2, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andLoginFailedTimeNotBetween(String value1, String value2) {
			addCriterion("LOGIN_FAILED_TIME not between", value1, value2, "loginFailedTime");
			return (Criteria) this;
		}

		public Criteria andTelphoneIsNull() {
			addCriterion("TELPHONE is null");
			return (Criteria) this;
		}

		public Criteria andTelphoneIsNotNull() {
			addCriterion("TELPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andTelphoneEqualTo(String value) {
			addCriterion("TELPHONE =", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotEqualTo(String value) {
			addCriterion("TELPHONE <>", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneGreaterThan(String value) {
			addCriterion("TELPHONE >", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
			addCriterion("TELPHONE >=", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLessThan(String value) {
			addCriterion("TELPHONE <", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLessThanOrEqualTo(String value) {
			addCriterion("TELPHONE <=", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLike(String value) {
			addCriterion("TELPHONE like", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotLike(String value) {
			addCriterion("TELPHONE not like", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneIn(List<String> values) {
			addCriterion("TELPHONE in", values, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotIn(List<String> values) {
			addCriterion("TELPHONE not in", values, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneBetween(String value1, String value2) {
			addCriterion("TELPHONE between", value1, value2, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotBetween(String value1, String value2) {
			addCriterion("TELPHONE not between", value1, value2, "telphone");
			return (Criteria) this;
		}

		public Criteria andFaxIsNull() {
			addCriterion("FAX is null");
			return (Criteria) this;
		}

		public Criteria andFaxIsNotNull() {
			addCriterion("FAX is not null");
			return (Criteria) this;
		}

		public Criteria andFaxEqualTo(String value) {
			addCriterion("FAX =", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotEqualTo(String value) {
			addCriterion("FAX <>", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThan(String value) {
			addCriterion("FAX >", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThanOrEqualTo(String value) {
			addCriterion("FAX >=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThan(String value) {
			addCriterion("FAX <", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThanOrEqualTo(String value) {
			addCriterion("FAX <=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLike(String value) {
			addCriterion("FAX like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotLike(String value) {
			addCriterion("FAX not like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxIn(List<String> values) {
			addCriterion("FAX in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotIn(List<String> values) {
			addCriterion("FAX not in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxBetween(String value1, String value2) {
			addCriterion("FAX between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotBetween(String value1, String value2) {
			addCriterion("FAX not between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameIsNull() {
			addCriterion("DEPARTMENT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameIsNotNull() {
			addCriterion("DEPARTMENT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameEqualTo(String value) {
			addCriterion("DEPARTMENT_NAME =", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameNotEqualTo(String value) {
			addCriterion("DEPARTMENT_NAME <>", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameGreaterThan(String value) {
			addCriterion("DEPARTMENT_NAME >", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
			addCriterion("DEPARTMENT_NAME >=", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameLessThan(String value) {
			addCriterion("DEPARTMENT_NAME <", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
			addCriterion("DEPARTMENT_NAME <=", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameLike(String value) {
			addCriterion("DEPARTMENT_NAME like", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameNotLike(String value) {
			addCriterion("DEPARTMENT_NAME not like", value, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameIn(List<String> values) {
			addCriterion("DEPARTMENT_NAME in", values, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameNotIn(List<String> values) {
			addCriterion("DEPARTMENT_NAME not in", values, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameBetween(String value1, String value2) {
			addCriterion("DEPARTMENT_NAME between", value1, value2, "departmentName");
			return (Criteria) this;
		}

		public Criteria andDepartmentNameNotBetween(String value1, String value2) {
			addCriterion("DEPARTMENT_NAME not between", value1, value2, "departmentName");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeIsNull() {
			addCriterion("FORBIDDEN_TIME is null");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeIsNotNull() {
			addCriterion("FORBIDDEN_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeEqualTo(String value) {
			addCriterion("FORBIDDEN_TIME =", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeNotEqualTo(String value) {
			addCriterion("FORBIDDEN_TIME <>", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeGreaterThan(String value) {
			addCriterion("FORBIDDEN_TIME >", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeGreaterThanOrEqualTo(String value) {
			addCriterion("FORBIDDEN_TIME >=", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeLessThan(String value) {
			addCriterion("FORBIDDEN_TIME <", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeLessThanOrEqualTo(String value) {
			addCriterion("FORBIDDEN_TIME <=", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeLike(String value) {
			addCriterion("FORBIDDEN_TIME like", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeNotLike(String value) {
			addCriterion("FORBIDDEN_TIME not like", value, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeIn(List<String> values) {
			addCriterion("FORBIDDEN_TIME in", values, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeNotIn(List<String> values) {
			addCriterion("FORBIDDEN_TIME not in", values, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeBetween(String value1, String value2) {
			addCriterion("FORBIDDEN_TIME between", value1, value2, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andForbiddenTimeNotBetween(String value1, String value2) {
			addCriterion("FORBIDDEN_TIME not between", value1, value2, "forbiddenTime");
			return (Criteria) this;
		}

		public Criteria andLockNumIsNull() {
			addCriterion("LOCK_NUM is null");
			return (Criteria) this;
		}

		public Criteria andLockNumIsNotNull() {
			addCriterion("LOCK_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andLockNumEqualTo(String value) {
			addCriterion("LOCK_NUM =", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumNotEqualTo(String value) {
			addCriterion("LOCK_NUM <>", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumGreaterThan(String value) {
			addCriterion("LOCK_NUM >", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumGreaterThanOrEqualTo(String value) {
			addCriterion("LOCK_NUM >=", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumLessThan(String value) {
			addCriterion("LOCK_NUM <", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumLessThanOrEqualTo(String value) {
			addCriterion("LOCK_NUM <=", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumLike(String value) {
			addCriterion("LOCK_NUM like", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumNotLike(String value) {
			addCriterion("LOCK_NUM not like", value, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumIn(List<String> values) {
			addCriterion("LOCK_NUM in", values, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumNotIn(List<String> values) {
			addCriterion("LOCK_NUM not in", values, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumBetween(String value1, String value2) {
			addCriterion("LOCK_NUM between", value1, value2, "lockNum");
			return (Criteria) this;
		}

		public Criteria andLockNumNotBetween(String value1, String value2) {
			addCriterion("LOCK_NUM not between", value1, value2, "lockNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumIsNull() {
			addCriterion("FORBIDDEN_NUM is null");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumIsNotNull() {
			addCriterion("FORBIDDEN_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumEqualTo(String value) {
			addCriterion("FORBIDDEN_NUM =", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumNotEqualTo(String value) {
			addCriterion("FORBIDDEN_NUM <>", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumGreaterThan(String value) {
			addCriterion("FORBIDDEN_NUM >", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumGreaterThanOrEqualTo(String value) {
			addCriterion("FORBIDDEN_NUM >=", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumLessThan(String value) {
			addCriterion("FORBIDDEN_NUM <", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumLessThanOrEqualTo(String value) {
			addCriterion("FORBIDDEN_NUM <=", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumLike(String value) {
			addCriterion("FORBIDDEN_NUM like", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumNotLike(String value) {
			addCriterion("FORBIDDEN_NUM not like", value, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumIn(List<String> values) {
			addCriterion("FORBIDDEN_NUM in", values, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumNotIn(List<String> values) {
			addCriterion("FORBIDDEN_NUM not in", values, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumBetween(String value1, String value2) {
			addCriterion("FORBIDDEN_NUM between", value1, value2, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andForbiddenNumNotBetween(String value1, String value2) {
			addCriterion("FORBIDDEN_NUM not between", value1, value2, "forbiddenNum");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionIsNull() {
			addCriterion("SECURITY_QUESTION is null");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionIsNotNull() {
			addCriterion("SECURITY_QUESTION is not null");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionEqualTo(String value) {
			addCriterion("SECURITY_QUESTION =", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionNotEqualTo(String value) {
			addCriterion("SECURITY_QUESTION <>", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionGreaterThan(String value) {
			addCriterion("SECURITY_QUESTION >", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionGreaterThanOrEqualTo(String value) {
			addCriterion("SECURITY_QUESTION >=", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionLessThan(String value) {
			addCriterion("SECURITY_QUESTION <", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionLessThanOrEqualTo(String value) {
			addCriterion("SECURITY_QUESTION <=", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionLike(String value) {
			addCriterion("SECURITY_QUESTION like", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionNotLike(String value) {
			addCriterion("SECURITY_QUESTION not like", value, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionIn(List<String> values) {
			addCriterion("SECURITY_QUESTION in", values, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionNotIn(List<String> values) {
			addCriterion("SECURITY_QUESTION not in", values, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionBetween(String value1, String value2) {
			addCriterion("SECURITY_QUESTION between", value1, value2, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityQuestionNotBetween(String value1, String value2) {
			addCriterion("SECURITY_QUESTION not between", value1, value2, "securityQuestion");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerIsNull() {
			addCriterion("SECURITY_ANSWER is null");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerIsNotNull() {
			addCriterion("SECURITY_ANSWER is not null");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerEqualTo(String value) {
			addCriterion("SECURITY_ANSWER =", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerNotEqualTo(String value) {
			addCriterion("SECURITY_ANSWER <>", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerGreaterThan(String value) {
			addCriterion("SECURITY_ANSWER >", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerGreaterThanOrEqualTo(String value) {
			addCriterion("SECURITY_ANSWER >=", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerLessThan(String value) {
			addCriterion("SECURITY_ANSWER <", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerLessThanOrEqualTo(String value) {
			addCriterion("SECURITY_ANSWER <=", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerLike(String value) {
			addCriterion("SECURITY_ANSWER like", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerNotLike(String value) {
			addCriterion("SECURITY_ANSWER not like", value, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerIn(List<String> values) {
			addCriterion("SECURITY_ANSWER in", values, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerNotIn(List<String> values) {
			addCriterion("SECURITY_ANSWER not in", values, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerBetween(String value1, String value2) {
			addCriterion("SECURITY_ANSWER between", value1, value2, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andSecurityAnswerNotBetween(String value1, String value2) {
			addCriterion("SECURITY_ANSWER not between", value1, value2, "securityAnswer");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdIsNull() {
			addCriterion("CHARGES_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdIsNotNull() {
			addCriterion("CHARGES_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdEqualTo(String value) {
			addCriterion("CHARGES_USER_ID =", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdNotEqualTo(String value) {
			addCriterion("CHARGES_USER_ID <>", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdGreaterThan(String value) {
			addCriterion("CHARGES_USER_ID >", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("CHARGES_USER_ID >=", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdLessThan(String value) {
			addCriterion("CHARGES_USER_ID <", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdLessThanOrEqualTo(String value) {
			addCriterion("CHARGES_USER_ID <=", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdLike(String value) {
			addCriterion("CHARGES_USER_ID like", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdNotLike(String value) {
			addCriterion("CHARGES_USER_ID not like", value, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdIn(List<String> values) {
			addCriterion("CHARGES_USER_ID in", values, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdNotIn(List<String> values) {
			addCriterion("CHARGES_USER_ID not in", values, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdBetween(String value1, String value2) {
			addCriterion("CHARGES_USER_ID between", value1, value2, "chargesUserId");
			return (Criteria) this;
		}

		public Criteria andChargesUserIdNotBetween(String value1, String value2) {
			addCriterion("CHARGES_USER_ID not between", value1, value2, "chargesUserId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_authority_user_t
	 * @mbggenerated  Fri May 04 17:34:15 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_authority_user_t
     *
     * @mbggenerated do_not_delete_during_merge Wed May 02 14:52:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}