package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompCaseIpsegmentT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.IPSEGMENT_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String ipsegmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.IPSEGMENT_DESC
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String ipsegmentDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String resPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String resPoolPartId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.IP_SUBNET
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String ipSubnet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.START_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String startIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.END_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String endIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.IP_TOTAL
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String ipTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.RELEASED
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String released;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.RELEASE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String releaseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_case_ipsegment_t.RELEASE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	private String releaseUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.CASE_ID
	 * @return  the value of comp_case_ipsegment_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.CASE_ID
	 * @param caseId  the value for comp_case_ipsegment_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.IPSEGMENT_ID
	 * @return  the value of comp_case_ipsegment_t.IPSEGMENT_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getIpsegmentId() {
		return ipsegmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.IPSEGMENT_ID
	 * @param ipsegmentId  the value for comp_case_ipsegment_t.IPSEGMENT_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setIpsegmentId(String ipsegmentId) {
		this.ipsegmentId = ipsegmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.IPSEGMENT_DESC
	 * @return  the value of comp_case_ipsegment_t.IPSEGMENT_DESC
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getIpsegmentDesc() {
		return ipsegmentDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.IPSEGMENT_DESC
	 * @param ipsegmentDesc  the value for comp_case_ipsegment_t.IPSEGMENT_DESC
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setIpsegmentDesc(String ipsegmentDesc) {
		this.ipsegmentDesc = ipsegmentDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.ORDER_ID
	 * @return  the value of comp_case_ipsegment_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.ORDER_ID
	 * @param orderId  the value for comp_case_ipsegment_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.APP_ID
	 * @return  the value of comp_case_ipsegment_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.APP_ID
	 * @param appId  the value for comp_case_ipsegment_t.APP_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.RES_POOL_ID
	 * @return  the value of comp_case_ipsegment_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getResPoolId() {
		return resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.RES_POOL_ID
	 * @param resPoolId  the value for comp_case_ipsegment_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setResPoolId(String resPoolId) {
		this.resPoolId = resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.RES_POOL_PART_ID
	 * @return  the value of comp_case_ipsegment_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getResPoolPartId() {
		return resPoolPartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.RES_POOL_PART_ID
	 * @param resPoolPartId  the value for comp_case_ipsegment_t.RES_POOL_PART_ID
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setResPoolPartId(String resPoolPartId) {
		this.resPoolPartId = resPoolPartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.IP_SUBNET
	 * @return  the value of comp_case_ipsegment_t.IP_SUBNET
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getIpSubnet() {
		return ipSubnet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.IP_SUBNET
	 * @param ipSubnet  the value for comp_case_ipsegment_t.IP_SUBNET
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setIpSubnet(String ipSubnet) {
		this.ipSubnet = ipSubnet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.START_IP
	 * @return  the value of comp_case_ipsegment_t.START_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getStartIp() {
		return startIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.START_IP
	 * @param startIp  the value for comp_case_ipsegment_t.START_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setStartIp(String startIp) {
		this.startIp = startIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.END_IP
	 * @return  the value of comp_case_ipsegment_t.END_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getEndIp() {
		return endIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.END_IP
	 * @param endIp  the value for comp_case_ipsegment_t.END_IP
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setEndIp(String endIp) {
		this.endIp = endIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.IP_TOTAL
	 * @return  the value of comp_case_ipsegment_t.IP_TOTAL
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getIpTotal() {
		return ipTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.IP_TOTAL
	 * @param ipTotal  the value for comp_case_ipsegment_t.IP_TOTAL
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setIpTotal(String ipTotal) {
		this.ipTotal = ipTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.CREATE_TIME
	 * @return  the value of comp_case_ipsegment_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.CREATE_TIME
	 * @param createTime  the value for comp_case_ipsegment_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.CREATE_USER
	 * @return  the value of comp_case_ipsegment_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.CREATE_USER
	 * @param createUser  the value for comp_case_ipsegment_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.RELEASED
	 * @return  the value of comp_case_ipsegment_t.RELEASED
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getReleased() {
		return released;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.RELEASED
	 * @param released  the value for comp_case_ipsegment_t.RELEASED
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setReleased(String released) {
		this.released = released;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.RELEASE_TIME
	 * @return  the value of comp_case_ipsegment_t.RELEASE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.RELEASE_TIME
	 * @param releaseTime  the value for comp_case_ipsegment_t.RELEASE_TIME
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setReleaseTime(String releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_case_ipsegment_t.RELEASE_USER
	 * @return  the value of comp_case_ipsegment_t.RELEASE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getReleaseUser() {
		return releaseUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_case_ipsegment_t.RELEASE_USER
	 * @param releaseUser  the value for comp_case_ipsegment_t.RELEASE_USER
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setReleaseUser(String releaseUser) {
		this.releaseUser = releaseUser;
	}
}