package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompResPoolTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public CompResPoolTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andResPoolIdIsNull() {
			addCriterion("RES_POOL_ID is null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIsNotNull() {
			addCriterion("RES_POOL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdEqualTo(String value) {
			addCriterion("RES_POOL_ID =", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotEqualTo(String value) {
			addCriterion("RES_POOL_ID <>", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThan(String value) {
			addCriterion("RES_POOL_ID >", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID >=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThan(String value) {
			addCriterion("RES_POOL_ID <", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID <=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLike(String value) {
			addCriterion("RES_POOL_ID like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotLike(String value) {
			addCriterion("RES_POOL_ID not like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIn(List<String> values) {
			addCriterion("RES_POOL_ID in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotIn(List<String> values) {
			addCriterion("RES_POOL_ID not in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID not between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolNameIsNull() {
			addCriterion("RES_POOL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andResPoolNameIsNotNull() {
			addCriterion("RES_POOL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolNameEqualTo(String value) {
			addCriterion("RES_POOL_NAME =", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameNotEqualTo(String value) {
			addCriterion("RES_POOL_NAME <>", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameGreaterThan(String value) {
			addCriterion("RES_POOL_NAME >", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_NAME >=", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameLessThan(String value) {
			addCriterion("RES_POOL_NAME <", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_NAME <=", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameLike(String value) {
			addCriterion("RES_POOL_NAME like", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameNotLike(String value) {
			addCriterion("RES_POOL_NAME not like", value, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameIn(List<String> values) {
			addCriterion("RES_POOL_NAME in", values, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameNotIn(List<String> values) {
			addCriterion("RES_POOL_NAME not in", values, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameBetween(String value1, String value2) {
			addCriterion("RES_POOL_NAME between", value1, value2, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolNameNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_NAME not between", value1, value2, "resPoolName");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneIsNull() {
			addCriterion("RES_POOL_ZONE is null");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneIsNotNull() {
			addCriterion("RES_POOL_ZONE is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneEqualTo(String value) {
			addCriterion("RES_POOL_ZONE =", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneNotEqualTo(String value) {
			addCriterion("RES_POOL_ZONE <>", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneGreaterThan(String value) {
			addCriterion("RES_POOL_ZONE >", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ZONE >=", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneLessThan(String value) {
			addCriterion("RES_POOL_ZONE <", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ZONE <=", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneLike(String value) {
			addCriterion("RES_POOL_ZONE like", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneNotLike(String value) {
			addCriterion("RES_POOL_ZONE not like", value, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneIn(List<String> values) {
			addCriterion("RES_POOL_ZONE in", values, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneNotIn(List<String> values) {
			addCriterion("RES_POOL_ZONE not in", values, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneBetween(String value1, String value2) {
			addCriterion("RES_POOL_ZONE between", value1, value2, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolZoneNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_ZONE not between", value1, value2, "resPoolZone");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlIsNull() {
			addCriterion("RES_POOL_URL is null");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlIsNotNull() {
			addCriterion("RES_POOL_URL is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlEqualTo(String value) {
			addCriterion("RES_POOL_URL =", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlNotEqualTo(String value) {
			addCriterion("RES_POOL_URL <>", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlGreaterThan(String value) {
			addCriterion("RES_POOL_URL >", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_URL >=", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlLessThan(String value) {
			addCriterion("RES_POOL_URL <", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_URL <=", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlLike(String value) {
			addCriterion("RES_POOL_URL like", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlNotLike(String value) {
			addCriterion("RES_POOL_URL not like", value, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlIn(List<String> values) {
			addCriterion("RES_POOL_URL in", values, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlNotIn(List<String> values) {
			addCriterion("RES_POOL_URL not in", values, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlBetween(String value1, String value2) {
			addCriterion("RES_POOL_URL between", value1, value2, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andResPoolUrlNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_URL not between", value1, value2, "resPoolUrl");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserPwdIsNull() {
			addCriterion("USER_PWD is null");
			return (Criteria) this;
		}

		public Criteria andUserPwdIsNotNull() {
			addCriterion("USER_PWD is not null");
			return (Criteria) this;
		}

		public Criteria andUserPwdEqualTo(String value) {
			addCriterion("USER_PWD =", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotEqualTo(String value) {
			addCriterion("USER_PWD <>", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdGreaterThan(String value) {
			addCriterion("USER_PWD >", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_PWD >=", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLessThan(String value) {
			addCriterion("USER_PWD <", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLessThanOrEqualTo(String value) {
			addCriterion("USER_PWD <=", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLike(String value) {
			addCriterion("USER_PWD like", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotLike(String value) {
			addCriterion("USER_PWD not like", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdIn(List<String> values) {
			addCriterion("USER_PWD in", values, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotIn(List<String> values) {
			addCriterion("USER_PWD not in", values, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdBetween(String value1, String value2) {
			addCriterion("USER_PWD between", value1, value2, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotBetween(String value1, String value2) {
			addCriterion("USER_PWD not between", value1, value2, "userPwd");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(String value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(String value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(String value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(String value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLike(String value) {
			addCriterion("UPDATE_TIME like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotLike(String value) {
			addCriterion("UPDATE_TIME not like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<String> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<String> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("UPDATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("UPDATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("UPDATE_USER =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("UPDATE_USER <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("UPDATE_USER >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("UPDATE_USER <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("UPDATE_USER like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("UPDATE_USER not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("UPDATE_USER in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("UPDATE_USER not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("UPDATE_USER between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_res_pool_t
     *
     * @mbggenerated do_not_delete_during_merge Thu May 03 10:01:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}