package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompOrderTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public CompOrderTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("ORDER_ID like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("ORDER_ID not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("PARENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("PARENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(String value) {
			addCriterion("PARENT_ID =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(String value) {
			addCriterion("PARENT_ID <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(String value) {
			addCriterion("PARENT_ID >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(String value) {
			addCriterion("PARENT_ID >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(String value) {
			addCriterion("PARENT_ID <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(String value) {
			addCriterion("PARENT_ID <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLike(String value) {
			addCriterion("PARENT_ID like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotLike(String value) {
			addCriterion("PARENT_ID not like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<String> values) {
			addCriterion("PARENT_ID in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<String> values) {
			addCriterion("PARENT_ID not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(String value1, String value2) {
			addCriterion("PARENT_ID between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(String value1, String value2) {
			addCriterion("PARENT_ID not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIsNull() {
			addCriterion("EFFECTIVE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIsNotNull() {
			addCriterion("EFFECTIVE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeEqualTo(String value) {
			addCriterion("EFFECTIVE_TIME =", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotEqualTo(String value) {
			addCriterion("EFFECTIVE_TIME <>", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeGreaterThan(String value) {
			addCriterion("EFFECTIVE_TIME >", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeGreaterThanOrEqualTo(String value) {
			addCriterion("EFFECTIVE_TIME >=", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeLessThan(String value) {
			addCriterion("EFFECTIVE_TIME <", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeLessThanOrEqualTo(String value) {
			addCriterion("EFFECTIVE_TIME <=", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeLike(String value) {
			addCriterion("EFFECTIVE_TIME like", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotLike(String value) {
			addCriterion("EFFECTIVE_TIME not like", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIn(List<String> values) {
			addCriterion("EFFECTIVE_TIME in", values, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotIn(List<String> values) {
			addCriterion("EFFECTIVE_TIME not in", values, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeBetween(String value1, String value2) {
			addCriterion("EFFECTIVE_TIME between", value1, value2, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotBetween(String value1, String value2) {
			addCriterion("EFFECTIVE_TIME not between", value1, value2, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeIsNull() {
			addCriterion("LENGTH_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLengthTimeIsNotNull() {
			addCriterion("LENGTH_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLengthTimeEqualTo(Integer value) {
			addCriterion("LENGTH_TIME =", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeNotEqualTo(Integer value) {
			addCriterion("LENGTH_TIME <>", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeGreaterThan(Integer value) {
			addCriterion("LENGTH_TIME >", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("LENGTH_TIME >=", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeLessThan(Integer value) {
			addCriterion("LENGTH_TIME <", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeLessThanOrEqualTo(Integer value) {
			addCriterion("LENGTH_TIME <=", value, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeIn(List<Integer> values) {
			addCriterion("LENGTH_TIME in", values, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeNotIn(List<Integer> values) {
			addCriterion("LENGTH_TIME not in", values, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeBetween(Integer value1, Integer value2) {
			addCriterion("LENGTH_TIME between", value1, value2, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("LENGTH_TIME not between", value1, value2, "lengthTime");
			return (Criteria) this;
		}

		public Criteria andLengthUnitIsNull() {
			addCriterion("LENGTH_UNIT is null");
			return (Criteria) this;
		}

		public Criteria andLengthUnitIsNotNull() {
			addCriterion("LENGTH_UNIT is not null");
			return (Criteria) this;
		}

		public Criteria andLengthUnitEqualTo(String value) {
			addCriterion("LENGTH_UNIT =", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitNotEqualTo(String value) {
			addCriterion("LENGTH_UNIT <>", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitGreaterThan(String value) {
			addCriterion("LENGTH_UNIT >", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitGreaterThanOrEqualTo(String value) {
			addCriterion("LENGTH_UNIT >=", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitLessThan(String value) {
			addCriterion("LENGTH_UNIT <", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitLessThanOrEqualTo(String value) {
			addCriterion("LENGTH_UNIT <=", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitLike(String value) {
			addCriterion("LENGTH_UNIT like", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitNotLike(String value) {
			addCriterion("LENGTH_UNIT not like", value, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitIn(List<String> values) {
			addCriterion("LENGTH_UNIT in", values, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitNotIn(List<String> values) {
			addCriterion("LENGTH_UNIT not in", values, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitBetween(String value1, String value2) {
			addCriterion("LENGTH_UNIT between", value1, value2, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andLengthUnitNotBetween(String value1, String value2) {
			addCriterion("LENGTH_UNIT not between", value1, value2, "lengthUnit");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(String value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(String value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(String value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(String value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLike(String value) {
			addCriterion("UPDATE_TIME like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotLike(String value) {
			addCriterion("UPDATE_TIME not like", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<String> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<String> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(String value1, String value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("UPDATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("UPDATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("UPDATE_USER =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("UPDATE_USER <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("UPDATE_USER >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("UPDATE_USER <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("UPDATE_USER like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("UPDATE_USER not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("UPDATE_USER in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("UPDATE_USER not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("UPDATE_USER between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIsNull() {
			addCriterion("CASE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIsNotNull() {
			addCriterion("CASE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeEqualTo(String value) {
			addCriterion("CASE_TYPE =", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeNotEqualTo(String value) {
			addCriterion("CASE_TYPE <>", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeGreaterThan(String value) {
			addCriterion("CASE_TYPE >", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE >=", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeLessThan(String value) {
			addCriterion("CASE_TYPE <", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeLessThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE <=", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeLike(String value) {
			addCriterion("CASE_TYPE like", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeNotLike(String value) {
			addCriterion("CASE_TYPE not like", value, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIn(List<String> values) {
			addCriterion("CASE_TYPE in", values, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeNotIn(List<String> values) {
			addCriterion("CASE_TYPE not in", values, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeBetween(String value1, String value2) {
			addCriterion("CASE_TYPE between", value1, value2, "caseType");
			return (Criteria) this;
		}

		public Criteria andCaseTypeNotBetween(String value1, String value2) {
			addCriterion("CASE_TYPE not between", value1, value2, "caseType");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIsNull() {
			addCriterion("EXPIRE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIsNotNull() {
			addCriterion("EXPIRE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andExpireTimeEqualTo(String value) {
			addCriterion("EXPIRE_TIME =", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotEqualTo(String value) {
			addCriterion("EXPIRE_TIME <>", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeGreaterThan(String value) {
			addCriterion("EXPIRE_TIME >", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeGreaterThanOrEqualTo(String value) {
			addCriterion("EXPIRE_TIME >=", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeLessThan(String value) {
			addCriterion("EXPIRE_TIME <", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeLessThanOrEqualTo(String value) {
			addCriterion("EXPIRE_TIME <=", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeLike(String value) {
			addCriterion("EXPIRE_TIME like", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotLike(String value) {
			addCriterion("EXPIRE_TIME not like", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIn(List<String> values) {
			addCriterion("EXPIRE_TIME in", values, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotIn(List<String> values) {
			addCriterion("EXPIRE_TIME not in", values, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeBetween(String value1, String value2) {
			addCriterion("EXPIRE_TIME between", value1, value2, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotBetween(String value1, String value2) {
			addCriterion("EXPIRE_TIME not between", value1, value2, "expireTime");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("APP_ID is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("APP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("APP_ID =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("APP_ID <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("APP_ID >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("APP_ID >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("APP_ID <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("APP_ID <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("APP_ID like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("APP_ID not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("APP_ID in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("APP_ID not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("APP_ID between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("APP_ID not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIsNull() {
			addCriterion("RES_POOL_ID is null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIsNotNull() {
			addCriterion("RES_POOL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdEqualTo(String value) {
			addCriterion("RES_POOL_ID =", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotEqualTo(String value) {
			addCriterion("RES_POOL_ID <>", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThan(String value) {
			addCriterion("RES_POOL_ID >", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID >=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThan(String value) {
			addCriterion("RES_POOL_ID <", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID <=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLike(String value) {
			addCriterion("RES_POOL_ID like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotLike(String value) {
			addCriterion("RES_POOL_ID not like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIn(List<String> values) {
			addCriterion("RES_POOL_ID in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotIn(List<String> values) {
			addCriterion("RES_POOL_ID not in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID not between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidIsNull() {
			addCriterion("vmModifyBatchId is null");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidIsNotNull() {
			addCriterion("vmModifyBatchId is not null");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidEqualTo(String value) {
			addCriterion("vmModifyBatchId =", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidNotEqualTo(String value) {
			addCriterion("vmModifyBatchId <>", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidGreaterThan(String value) {
			addCriterion("vmModifyBatchId >", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidGreaterThanOrEqualTo(String value) {
			addCriterion("vmModifyBatchId >=", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidLessThan(String value) {
			addCriterion("vmModifyBatchId <", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidLessThanOrEqualTo(String value) {
			addCriterion("vmModifyBatchId <=", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidLike(String value) {
			addCriterion("vmModifyBatchId like", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidNotLike(String value) {
			addCriterion("vmModifyBatchId not like", value, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidIn(List<String> values) {
			addCriterion("vmModifyBatchId in", values, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidNotIn(List<String> values) {
			addCriterion("vmModifyBatchId not in", values, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidBetween(String value1, String value2) {
			addCriterion("vmModifyBatchId between", value1, value2, "vmmodifybatchid");
			return (Criteria) this;
		}

		public Criteria andVmmodifybatchidNotBetween(String value1, String value2) {
			addCriterion("vmModifyBatchId not between", value1, value2, "vmmodifybatchid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_order_t
     *
     * @mbggenerated do_not_delete_during_merge Thu May 03 10:54:35 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}