package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompOrderT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.PARENT_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.EFFECTIVE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String effectiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.LENGTH_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private Integer lengthTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.LENGTH_UNIT
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String lengthUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.CASE_TYPE
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String caseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.EXPIRE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String expireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.APP_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String resPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_order_t.vmModifyBatchId
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	private String vmmodifybatchid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.ORDER_ID
	 * @return  the value of comp_order_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.ORDER_ID
	 * @param orderId  the value for comp_order_t.ORDER_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.PARENT_ID
	 * @return  the value of comp_order_t.PARENT_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.PARENT_ID
	 * @param parentId  the value for comp_order_t.PARENT_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.STATUS
	 * @return  the value of comp_order_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.STATUS
	 * @param status  the value for comp_order_t.STATUS
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.EFFECTIVE_TIME
	 * @return  the value of comp_order_t.EFFECTIVE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.EFFECTIVE_TIME
	 * @param effectiveTime  the value for comp_order_t.EFFECTIVE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setEffectiveTime(String effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.LENGTH_TIME
	 * @return  the value of comp_order_t.LENGTH_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public Integer getLengthTime() {
		return lengthTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.LENGTH_TIME
	 * @param lengthTime  the value for comp_order_t.LENGTH_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setLengthTime(Integer lengthTime) {
		this.lengthTime = lengthTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.LENGTH_UNIT
	 * @return  the value of comp_order_t.LENGTH_UNIT
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getLengthUnit() {
		return lengthUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.LENGTH_UNIT
	 * @param lengthUnit  the value for comp_order_t.LENGTH_UNIT
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setLengthUnit(String lengthUnit) {
		this.lengthUnit = lengthUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.CREATE_TIME
	 * @return  the value of comp_order_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.CREATE_TIME
	 * @param createTime  the value for comp_order_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.CREATE_USER
	 * @return  the value of comp_order_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.CREATE_USER
	 * @param createUser  the value for comp_order_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.UPDATE_TIME
	 * @return  the value of comp_order_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.UPDATE_TIME
	 * @param updateTime  the value for comp_order_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.UPDATE_USER
	 * @return  the value of comp_order_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.UPDATE_USER
	 * @param updateUser  the value for comp_order_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.CASE_ID
	 * @return  the value of comp_order_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.CASE_ID
	 * @param caseId  the value for comp_order_t.CASE_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.CASE_TYPE
	 * @return  the value of comp_order_t.CASE_TYPE
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getCaseType() {
		return caseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.CASE_TYPE
	 * @param caseType  the value for comp_order_t.CASE_TYPE
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.EXPIRE_TIME
	 * @return  the value of comp_order_t.EXPIRE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.EXPIRE_TIME
	 * @param expireTime  the value for comp_order_t.EXPIRE_TIME
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setExpireTime(String expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.APP_ID
	 * @return  the value of comp_order_t.APP_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.APP_ID
	 * @param appId  the value for comp_order_t.APP_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.RES_POOL_ID
	 * @return  the value of comp_order_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getResPoolId() {
		return resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.RES_POOL_ID
	 * @param resPoolId  the value for comp_order_t.RES_POOL_ID
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setResPoolId(String resPoolId) {
		this.resPoolId = resPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_order_t.vmModifyBatchId
	 * @return  the value of comp_order_t.vmModifyBatchId
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public String getVmmodifybatchid() {
		return vmmodifybatchid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_order_t.vmModifyBatchId
	 * @param vmmodifybatchid  the value for comp_order_t.vmModifyBatchId
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	public void setVmmodifybatchid(String vmmodifybatchid) {
		this.vmmodifybatchid = vmmodifybatchid;
	}
}