package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompAppT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.APP_NAME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String appName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.CREATE_FLAG
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String createFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.APP_CONTACTS
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String appContacts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_app_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.APP_ID
	 * @return  the value of comp_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.APP_ID
	 * @param appId  the value for comp_app_t.APP_ID
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.APP_NAME
	 * @return  the value of comp_app_t.APP_NAME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.APP_NAME
	 * @param appName  the value for comp_app_t.APP_NAME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setAppName(String appName) {
		this.appName = appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.DESCRIPTION
	 * @return  the value of comp_app_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.DESCRIPTION
	 * @param description  the value for comp_app_t.DESCRIPTION
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.CREATE_FLAG
	 * @return  the value of comp_app_t.CREATE_FLAG
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getCreateFlag() {
		return createFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.CREATE_FLAG
	 * @param createFlag  the value for comp_app_t.CREATE_FLAG
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setCreateFlag(String createFlag) {
		this.createFlag = createFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.APP_CONTACTS
	 * @return  the value of comp_app_t.APP_CONTACTS
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getAppContacts() {
		return appContacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.APP_CONTACTS
	 * @param appContacts  the value for comp_app_t.APP_CONTACTS
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setAppContacts(String appContacts) {
		this.appContacts = appContacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.CREATE_TIME
	 * @return  the value of comp_app_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.CREATE_TIME
	 * @param createTime  the value for comp_app_t.CREATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.CREATE_USER
	 * @return  the value of comp_app_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.CREATE_USER
	 * @param createUser  the value for comp_app_t.CREATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.UPDATE_TIME
	 * @return  the value of comp_app_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.UPDATE_TIME
	 * @param updateTime  the value for comp_app_t.UPDATE_TIME
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_app_t.UPDATE_USER
	 * @return  the value of comp_app_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_app_t.UPDATE_USER
	 * @param updateUser  the value for comp_app_t.UPDATE_USER
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}