package com.neusoft.mid.comp.boss.mybatis.bean;

public class CompBossOrderT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.BOSS_ORDER_ID
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String bossOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.OPERATE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String operateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.REASON_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String reasonType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.AGREEMENT_BEGING_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String agreementBegingTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.AGREEMENT_END_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String agreementEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.RESOURCE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String resourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.CHARGE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String chargeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.PRICE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.PAYMENT_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String paymentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.TIME_STAMP
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String timeStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_boss_order_t.STATUS
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.BOSS_ORDER_ID
	 * @return  the value of comp_boss_order_t.BOSS_ORDER_ID
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getBossOrderId() {
		return bossOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.BOSS_ORDER_ID
	 * @param bossOrderId  the value for comp_boss_order_t.BOSS_ORDER_ID
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setBossOrderId(String bossOrderId) {
		this.bossOrderId = bossOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.OPERATE_TYPE
	 * @return  the value of comp_boss_order_t.OPERATE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getOperateType() {
		return operateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.OPERATE_TYPE
	 * @param operateType  the value for comp_boss_order_t.OPERATE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.REASON_TYPE
	 * @return  the value of comp_boss_order_t.REASON_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getReasonType() {
		return reasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.REASON_TYPE
	 * @param reasonType  the value for comp_boss_order_t.REASON_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setReasonType(String reasonType) {
		this.reasonType = reasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.AGREEMENT_BEGING_TIME
	 * @return  the value of comp_boss_order_t.AGREEMENT_BEGING_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getAgreementBegingTime() {
		return agreementBegingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.AGREEMENT_BEGING_TIME
	 * @param agreementBegingTime  the value for comp_boss_order_t.AGREEMENT_BEGING_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setAgreementBegingTime(String agreementBegingTime) {
		this.agreementBegingTime = agreementBegingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.AGREEMENT_END_TIME
	 * @return  the value of comp_boss_order_t.AGREEMENT_END_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getAgreementEndTime() {
		return agreementEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.AGREEMENT_END_TIME
	 * @param agreementEndTime  the value for comp_boss_order_t.AGREEMENT_END_TIME
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setAgreementEndTime(String agreementEndTime) {
		this.agreementEndTime = agreementEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.RESOURCE_TYPE
	 * @return  the value of comp_boss_order_t.RESOURCE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getResourceType() {
		return resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.RESOURCE_TYPE
	 * @param resourceType  the value for comp_boss_order_t.RESOURCE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.CHARGE_TYPE
	 * @return  the value of comp_boss_order_t.CHARGE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getChargeType() {
		return chargeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.CHARGE_TYPE
	 * @param chargeType  the value for comp_boss_order_t.CHARGE_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.PRICE
	 * @return  the value of comp_boss_order_t.PRICE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.PRICE
	 * @param price  the value for comp_boss_order_t.PRICE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.PAYMENT_TYPE
	 * @return  the value of comp_boss_order_t.PAYMENT_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.PAYMENT_TYPE
	 * @param paymentType  the value for comp_boss_order_t.PAYMENT_TYPE
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.TIME_STAMP
	 * @return  the value of comp_boss_order_t.TIME_STAMP
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getTimeStamp() {
		return timeStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.TIME_STAMP
	 * @param timeStamp  the value for comp_boss_order_t.TIME_STAMP
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_boss_order_t.STATUS
	 * @return  the value of comp_boss_order_t.STATUS
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_boss_order_t.STATUS
	 * @param status  the value for comp_boss_order_t.STATUS
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}