package com.neusoft.mid.comp.boss.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class CompCaseIpsegmentTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public CompCaseIpsegmentTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdIsNull() {
			addCriterion("IPSEGMENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdIsNotNull() {
			addCriterion("IPSEGMENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdEqualTo(String value) {
			addCriterion("IPSEGMENT_ID =", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdNotEqualTo(String value) {
			addCriterion("IPSEGMENT_ID <>", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdGreaterThan(String value) {
			addCriterion("IPSEGMENT_ID >", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdGreaterThanOrEqualTo(String value) {
			addCriterion("IPSEGMENT_ID >=", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdLessThan(String value) {
			addCriterion("IPSEGMENT_ID <", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdLessThanOrEqualTo(String value) {
			addCriterion("IPSEGMENT_ID <=", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdLike(String value) {
			addCriterion("IPSEGMENT_ID like", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdNotLike(String value) {
			addCriterion("IPSEGMENT_ID not like", value, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdIn(List<String> values) {
			addCriterion("IPSEGMENT_ID in", values, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdNotIn(List<String> values) {
			addCriterion("IPSEGMENT_ID not in", values, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdBetween(String value1, String value2) {
			addCriterion("IPSEGMENT_ID between", value1, value2, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentIdNotBetween(String value1, String value2) {
			addCriterion("IPSEGMENT_ID not between", value1, value2, "ipsegmentId");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescIsNull() {
			addCriterion("IPSEGMENT_DESC is null");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescIsNotNull() {
			addCriterion("IPSEGMENT_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescEqualTo(String value) {
			addCriterion("IPSEGMENT_DESC =", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescNotEqualTo(String value) {
			addCriterion("IPSEGMENT_DESC <>", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescGreaterThan(String value) {
			addCriterion("IPSEGMENT_DESC >", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescGreaterThanOrEqualTo(String value) {
			addCriterion("IPSEGMENT_DESC >=", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescLessThan(String value) {
			addCriterion("IPSEGMENT_DESC <", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescLessThanOrEqualTo(String value) {
			addCriterion("IPSEGMENT_DESC <=", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescLike(String value) {
			addCriterion("IPSEGMENT_DESC like", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescNotLike(String value) {
			addCriterion("IPSEGMENT_DESC not like", value, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescIn(List<String> values) {
			addCriterion("IPSEGMENT_DESC in", values, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescNotIn(List<String> values) {
			addCriterion("IPSEGMENT_DESC not in", values, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescBetween(String value1, String value2) {
			addCriterion("IPSEGMENT_DESC between", value1, value2, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andIpsegmentDescNotBetween(String value1, String value2) {
			addCriterion("IPSEGMENT_DESC not between", value1, value2, "ipsegmentDesc");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("ORDER_ID like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("ORDER_ID not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("APP_ID is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("APP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("APP_ID =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("APP_ID <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("APP_ID >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("APP_ID >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("APP_ID <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("APP_ID <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("APP_ID like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("APP_ID not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("APP_ID in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("APP_ID not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("APP_ID between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("APP_ID not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIsNull() {
			addCriterion("RES_POOL_ID is null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIsNotNull() {
			addCriterion("RES_POOL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolIdEqualTo(String value) {
			addCriterion("RES_POOL_ID =", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotEqualTo(String value) {
			addCriterion("RES_POOL_ID <>", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThan(String value) {
			addCriterion("RES_POOL_ID >", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID >=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThan(String value) {
			addCriterion("RES_POOL_ID <", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_ID <=", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdLike(String value) {
			addCriterion("RES_POOL_ID like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotLike(String value) {
			addCriterion("RES_POOL_ID not like", value, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdIn(List<String> values) {
			addCriterion("RES_POOL_ID in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotIn(List<String> values) {
			addCriterion("RES_POOL_ID not in", values, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolIdNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_ID not between", value1, value2, "resPoolId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdIsNull() {
			addCriterion("RES_POOL_PART_ID is null");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdIsNotNull() {
			addCriterion("RES_POOL_PART_ID is not null");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdEqualTo(String value) {
			addCriterion("RES_POOL_PART_ID =", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdNotEqualTo(String value) {
			addCriterion("RES_POOL_PART_ID <>", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdGreaterThan(String value) {
			addCriterion("RES_POOL_PART_ID >", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdGreaterThanOrEqualTo(String value) {
			addCriterion("RES_POOL_PART_ID >=", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdLessThan(String value) {
			addCriterion("RES_POOL_PART_ID <", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdLessThanOrEqualTo(String value) {
			addCriterion("RES_POOL_PART_ID <=", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdLike(String value) {
			addCriterion("RES_POOL_PART_ID like", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdNotLike(String value) {
			addCriterion("RES_POOL_PART_ID not like", value, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdIn(List<String> values) {
			addCriterion("RES_POOL_PART_ID in", values, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdNotIn(List<String> values) {
			addCriterion("RES_POOL_PART_ID not in", values, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdBetween(String value1, String value2) {
			addCriterion("RES_POOL_PART_ID between", value1, value2, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andResPoolPartIdNotBetween(String value1, String value2) {
			addCriterion("RES_POOL_PART_ID not between", value1, value2, "resPoolPartId");
			return (Criteria) this;
		}

		public Criteria andIpSubnetIsNull() {
			addCriterion("IP_SUBNET is null");
			return (Criteria) this;
		}

		public Criteria andIpSubnetIsNotNull() {
			addCriterion("IP_SUBNET is not null");
			return (Criteria) this;
		}

		public Criteria andIpSubnetEqualTo(String value) {
			addCriterion("IP_SUBNET =", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetNotEqualTo(String value) {
			addCriterion("IP_SUBNET <>", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetGreaterThan(String value) {
			addCriterion("IP_SUBNET >", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetGreaterThanOrEqualTo(String value) {
			addCriterion("IP_SUBNET >=", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetLessThan(String value) {
			addCriterion("IP_SUBNET <", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetLessThanOrEqualTo(String value) {
			addCriterion("IP_SUBNET <=", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetLike(String value) {
			addCriterion("IP_SUBNET like", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetNotLike(String value) {
			addCriterion("IP_SUBNET not like", value, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetIn(List<String> values) {
			addCriterion("IP_SUBNET in", values, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetNotIn(List<String> values) {
			addCriterion("IP_SUBNET not in", values, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetBetween(String value1, String value2) {
			addCriterion("IP_SUBNET between", value1, value2, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andIpSubnetNotBetween(String value1, String value2) {
			addCriterion("IP_SUBNET not between", value1, value2, "ipSubnet");
			return (Criteria) this;
		}

		public Criteria andStartIpIsNull() {
			addCriterion("START_IP is null");
			return (Criteria) this;
		}

		public Criteria andStartIpIsNotNull() {
			addCriterion("START_IP is not null");
			return (Criteria) this;
		}

		public Criteria andStartIpEqualTo(String value) {
			addCriterion("START_IP =", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpNotEqualTo(String value) {
			addCriterion("START_IP <>", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpGreaterThan(String value) {
			addCriterion("START_IP >", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpGreaterThanOrEqualTo(String value) {
			addCriterion("START_IP >=", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpLessThan(String value) {
			addCriterion("START_IP <", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpLessThanOrEqualTo(String value) {
			addCriterion("START_IP <=", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpLike(String value) {
			addCriterion("START_IP like", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpNotLike(String value) {
			addCriterion("START_IP not like", value, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpIn(List<String> values) {
			addCriterion("START_IP in", values, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpNotIn(List<String> values) {
			addCriterion("START_IP not in", values, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpBetween(String value1, String value2) {
			addCriterion("START_IP between", value1, value2, "startIp");
			return (Criteria) this;
		}

		public Criteria andStartIpNotBetween(String value1, String value2) {
			addCriterion("START_IP not between", value1, value2, "startIp");
			return (Criteria) this;
		}

		public Criteria andEndIpIsNull() {
			addCriterion("END_IP is null");
			return (Criteria) this;
		}

		public Criteria andEndIpIsNotNull() {
			addCriterion("END_IP is not null");
			return (Criteria) this;
		}

		public Criteria andEndIpEqualTo(String value) {
			addCriterion("END_IP =", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpNotEqualTo(String value) {
			addCriterion("END_IP <>", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpGreaterThan(String value) {
			addCriterion("END_IP >", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpGreaterThanOrEqualTo(String value) {
			addCriterion("END_IP >=", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpLessThan(String value) {
			addCriterion("END_IP <", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpLessThanOrEqualTo(String value) {
			addCriterion("END_IP <=", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpLike(String value) {
			addCriterion("END_IP like", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpNotLike(String value) {
			addCriterion("END_IP not like", value, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpIn(List<String> values) {
			addCriterion("END_IP in", values, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpNotIn(List<String> values) {
			addCriterion("END_IP not in", values, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpBetween(String value1, String value2) {
			addCriterion("END_IP between", value1, value2, "endIp");
			return (Criteria) this;
		}

		public Criteria andEndIpNotBetween(String value1, String value2) {
			addCriterion("END_IP not between", value1, value2, "endIp");
			return (Criteria) this;
		}

		public Criteria andIpTotalIsNull() {
			addCriterion("IP_TOTAL is null");
			return (Criteria) this;
		}

		public Criteria andIpTotalIsNotNull() {
			addCriterion("IP_TOTAL is not null");
			return (Criteria) this;
		}

		public Criteria andIpTotalEqualTo(String value) {
			addCriterion("IP_TOTAL =", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalNotEqualTo(String value) {
			addCriterion("IP_TOTAL <>", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalGreaterThan(String value) {
			addCriterion("IP_TOTAL >", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalGreaterThanOrEqualTo(String value) {
			addCriterion("IP_TOTAL >=", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalLessThan(String value) {
			addCriterion("IP_TOTAL <", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalLessThanOrEqualTo(String value) {
			addCriterion("IP_TOTAL <=", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalLike(String value) {
			addCriterion("IP_TOTAL like", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalNotLike(String value) {
			addCriterion("IP_TOTAL not like", value, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalIn(List<String> values) {
			addCriterion("IP_TOTAL in", values, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalNotIn(List<String> values) {
			addCriterion("IP_TOTAL not in", values, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalBetween(String value1, String value2) {
			addCriterion("IP_TOTAL between", value1, value2, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andIpTotalNotBetween(String value1, String value2) {
			addCriterion("IP_TOTAL not between", value1, value2, "ipTotal");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andReleasedIsNull() {
			addCriterion("RELEASED is null");
			return (Criteria) this;
		}

		public Criteria andReleasedIsNotNull() {
			addCriterion("RELEASED is not null");
			return (Criteria) this;
		}

		public Criteria andReleasedEqualTo(String value) {
			addCriterion("RELEASED =", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedNotEqualTo(String value) {
			addCriterion("RELEASED <>", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedGreaterThan(String value) {
			addCriterion("RELEASED >", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedGreaterThanOrEqualTo(String value) {
			addCriterion("RELEASED >=", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedLessThan(String value) {
			addCriterion("RELEASED <", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedLessThanOrEqualTo(String value) {
			addCriterion("RELEASED <=", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedLike(String value) {
			addCriterion("RELEASED like", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedNotLike(String value) {
			addCriterion("RELEASED not like", value, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedIn(List<String> values) {
			addCriterion("RELEASED in", values, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedNotIn(List<String> values) {
			addCriterion("RELEASED not in", values, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedBetween(String value1, String value2) {
			addCriterion("RELEASED between", value1, value2, "released");
			return (Criteria) this;
		}

		public Criteria andReleasedNotBetween(String value1, String value2) {
			addCriterion("RELEASED not between", value1, value2, "released");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIsNull() {
			addCriterion("RELEASE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIsNotNull() {
			addCriterion("RELEASE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeEqualTo(String value) {
			addCriterion("RELEASE_TIME =", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotEqualTo(String value) {
			addCriterion("RELEASE_TIME <>", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeGreaterThan(String value) {
			addCriterion("RELEASE_TIME >", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeGreaterThanOrEqualTo(String value) {
			addCriterion("RELEASE_TIME >=", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeLessThan(String value) {
			addCriterion("RELEASE_TIME <", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeLessThanOrEqualTo(String value) {
			addCriterion("RELEASE_TIME <=", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeLike(String value) {
			addCriterion("RELEASE_TIME like", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotLike(String value) {
			addCriterion("RELEASE_TIME not like", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIn(List<String> values) {
			addCriterion("RELEASE_TIME in", values, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotIn(List<String> values) {
			addCriterion("RELEASE_TIME not in", values, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeBetween(String value1, String value2) {
			addCriterion("RELEASE_TIME between", value1, value2, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotBetween(String value1, String value2) {
			addCriterion("RELEASE_TIME not between", value1, value2, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseUserIsNull() {
			addCriterion("RELEASE_USER is null");
			return (Criteria) this;
		}

		public Criteria andReleaseUserIsNotNull() {
			addCriterion("RELEASE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseUserEqualTo(String value) {
			addCriterion("RELEASE_USER =", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserNotEqualTo(String value) {
			addCriterion("RELEASE_USER <>", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserGreaterThan(String value) {
			addCriterion("RELEASE_USER >", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserGreaterThanOrEqualTo(String value) {
			addCriterion("RELEASE_USER >=", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserLessThan(String value) {
			addCriterion("RELEASE_USER <", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserLessThanOrEqualTo(String value) {
			addCriterion("RELEASE_USER <=", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserLike(String value) {
			addCriterion("RELEASE_USER like", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserNotLike(String value) {
			addCriterion("RELEASE_USER not like", value, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserIn(List<String> values) {
			addCriterion("RELEASE_USER in", values, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserNotIn(List<String> values) {
			addCriterion("RELEASE_USER not in", values, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserBetween(String value1, String value2) {
			addCriterion("RELEASE_USER between", value1, value2, "releaseUser");
			return (Criteria) this;
		}

		public Criteria andReleaseUserNotBetween(String value1, String value2) {
			addCriterion("RELEASE_USER not between", value1, value2, "releaseUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comp_case_ipsegment_t
     *
     * @mbggenerated do_not_delete_during_merge Thu May 03 14:00:35 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}