-- 设置定时任务启动
set global event_scheduler=1;

/*湖北运营追加一下EVENT*/
-- ----------------------------
-- Event structure for COMP_STA_CAPACITY_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_CAPACITY_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_CAPACITY_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:20:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_CAPACITY_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_APP_DAY_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_APP_DAY_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_APP_DAY_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 02:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_APP_DAY_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_APP_DAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_APP_DAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_APP_DAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:45:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_APP_DAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_APP_WEEK_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_APP_WEEK_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_APP_WEEK_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:30:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_APP_WEEK_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_DAY_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_DAY_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_DAY_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 02:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_DAY_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_DISK_RT_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_DISK_RT_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_DISK_RT_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:20:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_DISK_RT_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_RT_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_RT_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_RT_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_RT_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_DEVICE_WEEK_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_WEEK_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_WEEK_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:25:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_WEEK_DEL_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_EBS_APP_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_EBS_APP_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_EBS_APP_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_EBS_APP_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPMPAR_APP_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPMPAR_APP_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPMPAR_APP_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPMPAR_APP_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPMPAR_DAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPMPAR_DAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPMPAR_DAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:30:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPMPAR_DAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPMPAR_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPMPAR_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPMPAR_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPMPAR_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPM_APP_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPM_APP_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPM_APP_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPM_APP_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPM_DAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPM_DAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPM_DAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:30:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPM_DAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_MINIPM_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_MINIPM_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_MINIPM_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_MINIPM_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_PM_APP_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_PM_APP_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_PM_APP_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_PM_APP_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_PM_DAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_PM_DAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_PM_DAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:30:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_PM_DAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_PM_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_PM_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_PM_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_PM_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_VM_APP_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_VM_APP_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_VM_APP_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:15:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_VM_APP_WEEK_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_VM_DAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_VM_DAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_VM_DAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:30:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_VM_DAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_VM_WEEK_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_VM_WEEK_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_VM_WEEK_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2015-01-01 01:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_VM_WEEK_PROC ()
;;
DELIMITER ;


-- ----------------------------
-- Event structure for COMP_STA_PM_HALFDAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_PM_HALFDAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_PM_HALFDAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2016-04-07 07:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_PM_HALFDAY_PROC ()
;;
DELIMITER ;

-- ----------------------------
-- Event structure for COMP_STA_VM_HALFDAY_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_VM_HALFDAY_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_VM_HALFDAY_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2016-04-07 07:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_VM_HALFDAY_PROC ()
;;
DELIMITER ;


-- ----------------------------
-- Event structure for COMP_STA_DEVICE_HALFDAY_DEL_EVENT
-- ----------------------------
DROP EVENT IF EXISTS `COMP_STA_DEVICE_HALFDAY_DEL_EVENT`;
DELIMITER ;;
CREATE EVENT `COMP_STA_DEVICE_HALFDAY_DEL_EVENT` ON SCHEDULE EVERY 1 DAY STARTS '2016-04-07 02:00:00' ON COMPLETION PRESERVE ENABLE DO CALL COMP_STA_DEVICE_HALFDAY_DEL_PROC ()
;;
DELIMITER ;