//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 07:09:20 
//


package com.neusoft.mid.cloong.schema.standard.pm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MeasureMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TemplateDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TemplateStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TemplateCreator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ServerTemplate")
public class ServerTemplate {

    @XmlElement(name = "TemplateID", required = true)
    protected String templateID;
    @XmlElement(name = "ResourceType", required = true)
    protected String resourceType;
    @XmlElement(name = "MeasureMode", required = true)
    protected String measureMode;
    @XmlElement(name = "TemplateDesc", required = true)
    protected String templateDesc;
    @XmlElement(name = "TemplateStatus", required = true)
    protected String templateStatus;
    @XmlElement(name = "TemplateCreator", required = true)
    protected String templateCreator;
    @XmlElement(name = "CreateTime", required = true)
    protected String createTime;
    @XmlElement(name = "ResourceInfo", required = true)
    protected ServerTemplate.ResourceInfo resourceInfo;

    /**
     * Gets the value of the templateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateID() {
        return templateID;
    }

    /**
     * Sets the value of the templateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateID(String value) {
        this.templateID = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the measureMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureMode() {
        return measureMode;
    }

    /**
     * Sets the value of the measureMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureMode(String value) {
        this.measureMode = value;
    }

    /**
     * Gets the value of the templateDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateDesc() {
        return templateDesc;
    }

    /**
     * Sets the value of the templateDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateDesc(String value) {
        this.templateDesc = value;
    }

    /**
     * Gets the value of the templateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateStatus() {
        return templateStatus;
    }

    /**
     * Sets the value of the templateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateStatus(String value) {
        this.templateStatus = value;
    }

    /**
     * Gets the value of the templateCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateCreator() {
        return templateCreator;
    }

    /**
     * Sets the value of the templateCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateCreator(String value) {
        this.templateCreator = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the resourceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServerTemplate.ResourceInfo }
     *     
     */
    public ServerTemplate.ResourceInfo getResourceInfo() {
        return resourceInfo;
    }

    /**
     * Sets the value of the resourceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerTemplate.ResourceInfo }
     *     
     */
    public void setResourceInfo(ServerTemplate.ResourceInfo value) {
        this.resourceInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ServerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serverType"
    })
    public static class ResourceInfo {

        @XmlElement(name = "ServerType", required = true)
        protected String serverType;

        /**
         * Gets the value of the serverType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerType() {
            return serverType;
        }

        /**
         * Sets the value of the serverType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerType(String value) {
            this.serverType = value;
        }

    }

}
