package com.neusoft.mid.cloong.vault.wsdl.services;

import com.neusoft.mid.iamp.logger.LogService;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-24T16:06:14.433+08:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "BussinessSupportService",
        wsdlLocation = "http://223.86.3.71:9080/JKService/webservices/BussinessSupportService?wsdl",
        targetNamespace = "http://ultrapower.com/BussinessSupportService")
public class BussinessSupportService extends Service {

    private static LogService log = LogService.getLogger(BussinessSupportService.class);

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ultrapower.com/BussinessSupportService", "BussinessSupportService");
    public final static QName BussinessSupportServiceHttpPort = new QName("http://ultrapower.com/BussinessSupportService", "BussinessSupportServiceHttpPort");
    static {
        URL url = null;
        try {
            /*Properties prop = new Properties();
            InputStream in = new BussinessSupportService().getClass().getResourceAsStream("/comm_conf/other/Properties.properties");
            //F:\workspace_idea522\cloong\COMP_Parent_SiChuan_34Phase\COMP_Portal\src\main\resources\comm_conf\other\Properties.properties
            try {
                prop.load(in);
            } catch (IOException e) {
                log.info("InputStream 解析失败" + e);
                e.printStackTrace();
            }
            //String httpHostlhx = prop.getProperty("httpHostlhx");
            String wsdlUrl = prop.getProperty("wsdl.url");
            //String wsdlUrl = ResourceBundle.getBundle("application-config", Locale.getDefault()).getString("wsdl.url");
            log.info("-------wsdl is-----" + wsdlUrl);*/

            url = new URL("http://223.86.3.71:9080/JKService/webservices/BussinessSupportService?wsdl");
            //url = new URL(wsdlUrl);
        } catch (MalformedURLException e) {
            log.info("-------wsdl exception-----" + e);
            java.util.logging.Logger.getLogger(BussinessSupportService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://223.86.3.71:9080/JKService/webservices/BussinessSupportService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BussinessSupportService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BussinessSupportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BussinessSupportService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /*public BussinessSupportService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BussinessSupportService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BussinessSupportService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/




    /**
     *
     * @return
     *     returns BussinessSupportServicePortType
     */
    @WebEndpoint(name = "BussinessSupportServiceHttpPort")
    public BussinessSupportServicePortType getBussinessSupportServiceHttpPort() {
        return super.getPort(BussinessSupportServiceHttpPort, BussinessSupportServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BussinessSupportServicePortType
     */
    @WebEndpoint(name = "BussinessSupportServiceHttpPort")
    public BussinessSupportServicePortType getBussinessSupportServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(BussinessSupportServiceHttpPort, BussinessSupportServicePortType.class, features);
    }

}
