package com.neusoft.mid.cloong.vault.wsdl.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-11-28T10:20:52.985+08:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://ultrapower.com/BussinessSupportService", name = "BussinessSupportServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BussinessSupportServicePortType {

    @WebMethod
    @RequestWrapper(localName = "connTest", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.ConnTest")
    @ResponseWrapper(localName = "connTestResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.ConnTestResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String connTest(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getPolicy4Fort", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.GetPolicy4Fort")
    @ResponseWrapper(localName = "getPolicy4FortResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.GetPolicy4FortResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String getPolicy4Fort(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0,
            @WebParam(name = "in1", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in2
    );

    @WebMethod
    @RequestWrapper(localName = "autoAuth", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.AutoAuth")
    @ResponseWrapper(localName = "autoAuthResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.AutoAuthResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String autoAuth(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryAppOperJKStatus", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryAppOperJKStatus")
    @ResponseWrapper(localName = "queryAppOperJKStatusResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryAppOperJKStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String queryAppOperJKStatus(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "reSendJKPass", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.ReSendJKPass")
    @ResponseWrapper(localName = "reSendJKPassResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.ReSendJKPassResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String reSendJKPass(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryLoginJKStatusForSelfStudy", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryLoginJKStatusForSelfStudy")
    @ResponseWrapper(localName = "queryLoginJKStatusForSelfStudyResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryLoginJKStatusForSelfStudyResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String queryLoginJKStatusForSelfStudy(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryResCmdJKStatus", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryResCmdJKStatus")
    @ResponseWrapper(localName = "queryResCmdJKStatusResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryResCmdJKStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String queryResCmdJKStatus(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "remoteAuth", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.RemoteAuth")
    @ResponseWrapper(localName = "remoteAuthResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.RemoteAuthResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String remoteAuth(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryLoginJKStatus", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryLoginJKStatus")
    @ResponseWrapper(localName = "queryLoginJKStatusResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryLoginJKStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String queryLoginJKStatus(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "createLoginRequest", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateLoginRequest")
    @ResponseWrapper(localName = "createLoginRequestResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateLoginRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String createLoginRequest(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "createResRequest", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateResRequest")
    @ResponseWrapper(localName = "createResRequestResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateResRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String createResRequest(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryJKStatusByID", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryJKStatusByID")
    @ResponseWrapper(localName = "queryJKStatusByIDResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.QueryJKStatusByIDResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String queryJKStatusByID(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "cancelRequest", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CancelRequest")
    @ResponseWrapper(localName = "cancelRequestResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CancelRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String cancelRequest(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "createAppRequest", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateAppRequest")
    @ResponseWrapper(localName = "createAppRequestResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.CreateAppRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String createAppRequest(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "localAuth", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.LocalAuth")
    @ResponseWrapper(localName = "localAuthResponse", targetNamespace = "http://ultrapower.com/BussinessSupportService", className = "com.ultrapower.bussinesssupportservice.LocalAuthResponse")
    @WebResult(name = "out", targetNamespace = "http://ultrapower.com/BussinessSupportService")
    public java.lang.String localAuth(

            @WebParam(name = "in0", targetNamespace = "http://ultrapower.com/BussinessSupportService")
                    java.lang.String in0
    );
}
