package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import com.neusoft.mid.comp.boss.mybatis.bean.CompBossOrderT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompBossOrderTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompBossOrderTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int countByExample(CompBossOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int deleteByExample(CompBossOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int insert(CompBossOrderT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int insertSelective(CompBossOrderT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	List<CompBossOrderT> selectByExample(CompBossOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompBossOrderT record,
			@Param("example") CompBossOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_boss_order_t
	 * @mbggenerated  Thu May 10 13:32:51 CST 2018
	 */
	int updateByExample(@Param("record") CompBossOrderT record, @Param("example") CompBossOrderTExample example);
}