package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import com.neusoft.mid.comp.boss.mybatis.bean.CompCaseIpsegmentT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompCaseIpsegmentTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompCaseIpsegmentTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int countByExample(CompCaseIpsegmentTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int deleteByExample(CompCaseIpsegmentTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int deleteByPrimaryKey(String caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int insert(CompCaseIpsegmentT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int insertSelective(CompCaseIpsegmentT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	List<CompCaseIpsegmentT> selectByExample(CompCaseIpsegmentTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	CompCaseIpsegmentT selectByPrimaryKey(String caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompCaseIpsegmentT record,
			@Param("example") CompCaseIpsegmentTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int updateByExample(@Param("record") CompCaseIpsegmentT record,
			@Param("example") CompCaseIpsegmentTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int updateByPrimaryKeySelective(CompCaseIpsegmentT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_ipsegment_t
	 * @mbggenerated  Fri May 04 17:34:46 CST 2018
	 */
	int updateByPrimaryKey(CompCaseIpsegmentT record);
}