package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.neusoft.mid.comp.boss.mybatis.bean.CompUserAuditLogT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompUserAuditLogTExample;

public interface CompUserAuditLogTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int countByExample(CompUserAuditLogTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int deleteByExample(CompUserAuditLogTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int insert(CompUserAuditLogT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int insertSelective(CompUserAuditLogT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	List<CompUserAuditLogT> selectByExample(CompUserAuditLogTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompUserAuditLogT record,
			@Param("example") CompUserAuditLogTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_user_audit_log_t
	 * @mbggenerated  Fri May 04 17:35:49 CST 2018
	 */
	int updateByExample(@Param("record") CompUserAuditLogT record, @Param("example") CompUserAuditLogTExample example);
}