package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import com.neusoft.mid.comp.boss.mybatis.bean.CompCaseVlanT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompCaseVlanTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompCaseVlanTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int countByExample(CompCaseVlanTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int deleteByExample(CompCaseVlanTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int deleteByPrimaryKey(String caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int insert(CompCaseVlanT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int insertSelective(CompCaseVlanT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	List<CompCaseVlanT> selectByExample(CompCaseVlanTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	CompCaseVlanT selectByPrimaryKey(String caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompCaseVlanT record, @Param("example") CompCaseVlanTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int updateByExample(@Param("record") CompCaseVlanT record, @Param("example") CompCaseVlanTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int updateByPrimaryKeySelective(CompCaseVlanT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_case_vlan_t
	 * @mbggenerated  Fri May 04 17:34:58 CST 2018
	 */
	int updateByPrimaryKey(CompCaseVlanT record);
}