package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.neusoft.mid.comp.boss.mybatis.bean.CompAuthorityUserAppT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompAuthorityUserAppTExample;

public interface CompAuthorityUserAppTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int countByExample(CompAuthorityUserAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int deleteByExample(CompAuthorityUserAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int insert(CompAuthorityUserAppT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int insertSelective(CompAuthorityUserAppT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	List<CompAuthorityUserAppT> selectByExample(CompAuthorityUserAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompAuthorityUserAppT record,
			@Param("example") CompAuthorityUserAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_authority_user_app_t
	 * @mbggenerated  Fri May 04 17:34:03 CST 2018
	 */
	int updateByExample(@Param("record") CompAuthorityUserAppT record,
			@Param("example") CompAuthorityUserAppTExample example);
}