package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import com.neusoft.mid.comp.boss.mybatis.bean.CompResPoolT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompResPoolTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompResPoolTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int countByExample(CompResPoolTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int deleteByExample(CompResPoolTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int deleteByPrimaryKey(String resPoolId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int insert(CompResPoolT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int insertSelective(CompResPoolT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	List<CompResPoolT> selectByExample(CompResPoolTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	CompResPoolT selectByPrimaryKey(String resPoolId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompResPoolT record, @Param("example") CompResPoolTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int updateByExample(@Param("record") CompResPoolT record, @Param("example") CompResPoolTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int updateByPrimaryKeySelective(CompResPoolT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_res_pool_t
	 * @mbggenerated  Fri May 04 17:35:26 CST 2018
	 */
	int updateByPrimaryKey(CompResPoolT record);
}