package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.neusoft.mid.comp.boss.mybatis.bean.CompAppT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompAppTExample;

public interface CompAppTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int countByExample(CompAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int deleteByExample(CompAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int deleteByPrimaryKey(String appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int insert(CompAppT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int insertSelective(CompAppT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	List<CompAppT> selectByExample(CompAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	CompAppT selectByPrimaryKey(String appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompAppT record, @Param("example") CompAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int updateByExample(@Param("record") CompAppT record, @Param("example") CompAppTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int updateByPrimaryKeySelective(CompAppT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_app_t
	 * @mbggenerated  Fri May 04 17:33:30 CST 2018
	 */
	int updateByPrimaryKey(CompAppT record);
}