package com.neusoft.mid.comp.boss.mybatis.xmlmapper;

import com.neusoft.mid.comp.boss.mybatis.bean.CompOrderT;
import com.neusoft.mid.comp.boss.mybatis.bean.CompOrderTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompOrderTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int countByExample(CompOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int deleteByExample(CompOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int insert(CompOrderT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int insertSelective(CompOrderT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	List<CompOrderT> selectByExample(CompOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	CompOrderT selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CompOrderT record, @Param("example") CompOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int updateByExample(@Param("record") CompOrderT record, @Param("example") CompOrderTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int updateByPrimaryKeySelective(CompOrderT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_order_t
	 * @mbggenerated  Fri May 04 17:35:11 CST 2018
	 */
	int updateByPrimaryKey(CompOrderT record);
}