package com.neusoft.mid.cloong.portmap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-05-15T14:13:33.610+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.CMCCCloud.com/wsdl/CMCC/SOAP/pc/services", name = "PortMapService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PortMapService {

    @WebResult(name = "createPortMapResponse", targetNamespace = "http://www.CMCCCloud.com/wsdl/CMCC/SOAP/pc/services", partName = "parameters")
    @WebMethod
    public CreatePortMapResponse createPortMap(
        @WebParam(partName = "parameters", name = "createPortMap", targetNamespace = "http://www.CMCCCloud.com/wsdl/CMCC/SOAP/pc/services")
        CreatePortMap parameters
    );

    @WebResult(name = "deletePortMapResponse", targetNamespace = "http://www.CMCCCloud.com/wsdl/CMCC/SOAP/pc/services", partName = "parameters")
    @WebMethod
    public DeletePortMapResponse deletePortMap(
        @WebParam(partName = "parameters", name = "deletePortMap", targetNamespace = "http://www.CMCCCloud.com/wsdl/CMCC/SOAP/pc/services")
        DeletePortMap parameters
    );
}
