package com.neusoft.mid.cloong.portmap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-05-15T14:13:33.614+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "PortMapServiceImplService", 
                  wsdlLocation = "file:/D:/sccomp/test/src/pc.wsdl",
                  targetNamespace = "http://service.rp.privatecloud.mid.neusoft.com/") 
public class PortMapServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.rp.privatecloud.mid.neusoft.com/", "PortMapServiceImplService");
    public final static QName PortMapServiceImplPort = new QName("http://service.rp.privatecloud.mid.neusoft.com/", "PortMapServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.10.127.167:8081/private_cloud_rs/pc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PortMapServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/sccomp/test/src/pc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PortMapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PortMapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortMapServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PortMapService
     */
    @WebEndpoint(name = "PortMapServiceImplPort")
    public PortMapService getPortMapServiceImplPort() {
        return super.getPort(PortMapServiceImplPort, PortMapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortMapService
     */
    @WebEndpoint(name = "PortMapServiceImplPort")
    public PortMapService getPortMapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PortMapServiceImplPort, PortMapService.class, features);
    }

}
